#!/usr/bin/env bash


#####################################################
# Created by cryptopool.builders for crypto use...
#####################################################
# Needs to be ran after the first reboot of the system after permissions are set
#####################################################

source /etc/functions.sh

sleep 5
echo "Removing junk coins from YiiMP, this will take several minutes to complete, do not restart server until done!"
hide_output yiimp checkup
hide_output yiimp coin MDT delete
hide_output yiimp coin FLAX delete
hide_output yiimp coin CHC delete
hide_output yiimp coin DRP delete
hide_output yiimp coin VTC delete
hide_output yiimp coin FTC delete
hide_output yiimp coin UFO delete
hide_output yiimp coin PXC delete
hide_output yiimp coin HAL delete
hide_output yiimp coin XAI delete
hide_output yiimp coin QRK delete
hide_output yiimp coin MUE delete
hide_output yiimp coin BOD delete
hide_output yiimp coin SRC delete
hide_output yiimp coin BTQ delete
hide_output yiimp coin GEO delete
hide_output yiimp coin DGB delete
hide_output yiimp coin CYP delete
hide_output yiimp coin IDC delete
hide_output yiimp coin NEOS delete
hide_output yiimp coin MYR delete
hide_output yiimp coin XDC delete
hide_output yiimp coin SKC delete
hide_output yiimp coin LOG delete
hide_output yiimp coin ILM delete
hide_output yiimp coin START delete
hide_output yiimp coin URO delete
hide_output yiimp coin DASH delete
hide_output yiimp coin BSC delete
hide_output yiimp coin HEDG delete
hide_output yiimp coin AMBER delete
hide_output yiimp coin HTML5 delete
hide_output yiimp coin ZRC delete
hide_output	yiimp coin UNF delete
hide_output	yiimp coin DES delete
hide_output	yiimp coin KUMA delete
hide_output	yiimp coin MEME delete
hide_output	yiimp coin FOOT delete
hide_output	yiimp coin UMO delete
hide_output	yiimp coin G3N delete
hide_output	yiimp coin SHND delete
hide_output	yiimp coin WHIPPED delete
hide_output	yiimp coin FLY delete
hide_output	yiimp coin BUMBA delete
hide_output	yiimp coin EBG delete
hide_output	yiimp coin I0C delete
hide_output	yiimp coin CAPT delete
hide_output	yiimp coin PAK delete
hide_output	yiimp coin EUC delete
hide_output	yiimp coin GRE-OLD delete
hide_output	yiimp coin PR delete
hide_output	yiimp coin VGC delete
hide_output	yiimp coin CFC delete
hide_output	yiimp coin GAME delete
hide_output	yiimp coin FONZ delete
hide_output	yiimp coin DBIC delete
hide_output	yiimp coin TRUMP delete
hide_output	yiimp coin JIF delete
hide_output	yiimp coin EVIL delete
hide_output	yiimp coin EVO delete
hide_output	yiimp coin LTCR delete
hide_output	yiimp coin SANDG delete
hide_output	yiimp coin RICHX delete
hide_output	yiimp coin ADZ delete
hide_output	yiimp coin DGCS delete
hide_output	yiimp coin BOLI delete
hide_output	yiimp coin LGBTQ delete
hide_output	yiimp coin ZOOM delete
hide_output	yiimp coin YOC delete
hide_output	yiimp coin SIB delete
hide_output	yiimp coin OPES delete
hide_output	yiimp coin NKC delete
hide_output	yiimp coin MMXVI delete
hide_output	yiimp coin MBL delete
hide_output	yiimp coin KNC delete
hide_output	yiimp coin AR2 delete
hide_output	yiimp coin AND delete
hide_output	yiimp coin TROLL delete
hide_output	yiimp coin DNET delete
hide_output	yiimp coin DCR delete
hide_output	yiimp coin EGC delete
hide_output	yiimp coin MND delete
hide_output	yiimp coin BNT delete
hide_output	yiimp coin AMS delete
hide_output	yiimp coin INFX delete
hide_output	yiimp coin BSD delete
hide_output	yiimp coin HTC delete
hide_output	yiimp coin CZECO delete
hide_output	yiimp coin EDRC delete
hide_output	yiimp coin FTP delete
hide_output	yiimp coin OP delete
hide_output	yiimp coin CHAI delete
hide_output	yiimp coin REV delete
hide_output	yiimp coin PULSE delete
hide_output	yiimp coin XCT delete
hide_output	yiimp coin STS delete
hide_output	yiimp coin EC delete
hide_output	yiimp coin CYG delete
hide_output	yiimp coin VAL delete
hide_output	yiimp coin TBC delete
hide_output	yiimp coin CRBIT delete
hide_output	yiimp coin GMX delete
hide_output	yiimp coin HODL delete
hide_output	yiimp coin KLC delete
hide_output	yiimp coin BUZZ delete
hide_output	yiimp coin ADCN delete
hide_output	yiimp coin RBIES delete
hide_output	yiimp coin SEC delete
hide_output	yiimp coin XID delete
hide_output	yiimp coin BTCU delete
hide_output	yiimp coin WARP delete
hide_output	yiimp coin CPNC delete
hide_output	yiimp coin HIRE delete
hide_output	yiimp coin SLS delete
hide_output	yiimp coin XHI delete
hide_output	yiimp coin RADS delete
hide_output	yiimp coin BTP delete
hide_output	yiimp coin X2 delete
hide_output	yiimp coin HMP delete
hide_output	yiimp coin BRONZ delete
hide_output	yiimp coin RUBIT delete
hide_output	yiimp coin REP delete
hide_output	yiimp coin SPL delete
hide_output	yiimp coin CIONZ delete
hide_output	yiimp coin SCRT delete
hide_output	yiimp coin DEUR delete
hide_output	yiimp coin VOX delete
hide_output	yiimp coin CLUB delete
hide_output	yiimp coin SCOT delete
hide_output	yiimp coin FLOZ delete
hide_output	yiimp coin STATS delete
hide_output	yiimp coin HZDOGE delete
hide_output	yiimp coin WLC delete
hide_output	yiimp coin BITUSD delete
hide_output	yiimp coin BITCNY delete
hide_output	yiimp coin FNX delete
hide_output	yiimp coin APC delete
hide_output	yiimp coin XLM delete
hide_output	yiimp coin AGRS delete
hide_output	yiimp coin DROP delete
hide_output	yiimp coin AMP delete
hide_output	yiimp coin ANTI delete
hide_output	yiimp coin 1337 delete
hide_output	yiimp coin TRBO delete
hide_output	yiimp coin BIC delete
hide_output	yiimp coin SOIL delete
hide_output	yiimp coin OMNI delete
hide_output	yiimp coin CUBE delete
hide_output	yiimp coin BAC delete
hide_output	yiimp coin WOP delete
hide_output	yiimp coin FCT delete
hide_output	yiimp coin PRT delete
hide_output	yiimp coin CBIT delete
hide_output	yiimp coin NEU delete
hide_output	yiimp coin STEPS delete
hide_output	yiimp coin EXP delete
hide_output	yiimp coin BCY delete
hide_output	yiimp coin PRIME delete
hide_output	yiimp coin SHF delete
hide_output	yiimp coin SWING delete
hide_output	yiimp coin MI delete
hide_output	yiimp coin MACRO delete
hide_output	yiimp coin SC delete
hide_output	yiimp coin GCR delete
hide_output	yiimp coin MAPC delete
hide_output	yiimp coin GCC delete
hide_output	yiimp coin TX delete
hide_output	yiimp coin ETH delete
hide_output	yiimp coin CRE delete
hide_output	yiimp coin AEON delete
hide_output	yiimp coin GSY delete
hide_output	yiimp coin CHIP delete
hide_output	yiimp coin BTCHC delete
hide_output	yiimp coin AXIOM delete
hide_output	yiimp coin FUEL delete
hide_output	yiimp coin BIOS delete
hide_output	yiimp coin CPC delete
hide_output	yiimp coin IBITS delete
hide_output	yiimp coin DIGS delete
hide_output	yiimp coin NOC delete
hide_output	yiimp coin MCZ delete
hide_output	yiimp coin BANX delete
hide_output	yiimp coin CPN delete
hide_output	yiimp coin SPRTS delete
hide_output	yiimp coin SPROUT delete
hide_output	yiimp coin NUKE delete
hide_output	yiimp coin 2BACCO delete
hide_output	yiimp coin FIC delete
hide_output	yiimp coin LFO delete
hide_output	yiimp coin VERSA delete
hide_output	yiimp coin MCAR delete
hide_output	yiimp coin CARB delete
hide_output	yiimp coin ZUR delete
hide_output	yiimp coin VAPE delete
hide_output	yiimp coin TALK delete
hide_output	yiimp coin RUM delete
hide_output	yiimp coin PPCD delete
hide_output	yiimp coin PHO delete
hide_output	yiimp coin P0001 delete
hide_output	yiimp coin NODE delete
hide_output	yiimp coin MRC delete
hide_output	yiimp coin ISO delete
hide_output	yiimp coin HANSA delete
hide_output	yiimp coin FX01 delete
hide_output	yiimp coin FRSH delete
hide_output	yiimp coin FIMK delete
hide_output	yiimp coin FAIL delete
hide_output	yiimp coin DRM delete
hide_output	yiimp coin DRK delete
hide_output	yiimp coin CV2 delete
hide_output	yiimp coin BTRHA delete
hide_output	yiimp coin ALCUREX delete
hide_output	yiimp coin BNX delete
hide_output	yiimp coin QUIT delete
hide_output	yiimp coin V delete
hide_output	yiimp coin PLC delete
hide_output	yiimp coin GRW delete
hide_output	yiimp coin DUO delete
hide_output	yiimp coin ANI delete
hide_output	yiimp coin CDC delete
hide_output	yiimp coin CX delete
hide_output	yiimp coin MARS delete
hide_output	yiimp coin SHA delete
hide_output	yiimp coin FETISH delete
hide_output	yiimp coin EXC delete
hide_output	yiimp coin BDSM delete
hide_output	yiimp coin OFF delete
hide_output	yiimp coin EMC delete
hide_output	yiimp coin BLZ delete
hide_output	yiimp coin CHAO delete
hide_output	yiimp coin CNO delete
hide_output	yiimp coin FUNK delete
hide_output	yiimp coin UNIC delete
hide_output	yiimp coin DUCK delete
hide_output	yiimp coin BSY delete
hide_output	yiimp coin SPN delete
hide_output	yiimp coin IPC delete
hide_output	yiimp coin '$MINEZ' delete
hide_output	yiimp coin '$MINEW' delete
hide_output	yiimp coin ADD delete
hide_output	yiimp coin '$MINE' delete
hide_output	yiimp coin FTCC delete
hide_output	yiimp coin CIV delete
hide_output	yiimp coin TOP delete
hide_output	yiimp coin TTY delete
hide_output	yiimp coin NTC delete
hide_output	yiimp coin KIWI delete
hide_output	yiimp coin XPL delete
hide_output	yiimp coin XGR delete
hide_output	yiimp coin '$$$' delete
hide_output	yiimp coin 66 delete
hide_output	yiimp coin MDC delete
hide_output	yiimp coin SVC delete
hide_output	yiimp coin DARK delete
hide_output	yiimp coin POP delete
hide_output	yiimp coin WSX delete
hide_output	yiimp coin DOT delete
hide_output	yiimp coin YOVI delete
hide_output	yiimp coin HXX delete
hide_output	yiimp coin CRPS delete
hide_output	yiimp coin BAM delete
hide_output	yiimp coin SJW delete
hide_output	yiimp coin GMCX delete
hide_output	yiimp coin SPX delete
hide_output	yiimp coin EXT delete
hide_output	yiimp coin TENNET delete
hide_output	yiimp coin KC delete
hide_output	yiimp coin BLUS delete
hide_output	yiimp coin XRA delete
hide_output	yiimp coin SPEC delete
hide_output	yiimp coin EA delete
hide_output	yiimp coin TAGR delete
hide_output	yiimp coin HAZE delete
hide_output	yiimp coin TAM delete
hide_output	yiimp coin POLY delete
hide_output	yiimp coin INDEX delete
hide_output	yiimp coin GENI delete
hide_output	yiimp coin BUCKS delete
hide_output	yiimp coin SPKTR delete
hide_output	yiimp coin GENE delete
hide_output	yiimp coin GRM delete
hide_output yiimp coin DIBS delete
hide_output	yiimp coin GTFO delete
hide_output	yiimp coin FUTC delete
hide_output	yiimp coin XVI delete
hide_output	yiimp coin GLOBE delete
hide_output	yiimp coin SMSR delete
hide_output	yiimp coin CIRC delete
hide_output	yiimp coin WOC2 delete
hide_output	yiimp coin NODX delete
hide_output	yiimp coin ERC delete
hide_output	yiimp coin SEN delete
hide_output	yiimp coin SAK delete
hide_output	yiimp coin EOC delete
hide_output	yiimp coin TRANSF delete
hide_output	yiimp coin GEN delete
hide_output	yiimp coin DRKT delete
hide_output	yiimp coin XCE delete
hide_output	yiimp coin XPH delete
hide_output	yiimp coin FIST delete
hide_output	yiimp coin DUB delete
hide_output	yiimp coin VAPOR delete
hide_output	yiimp coin ARPA delete
hide_output	yiimp coin BNB delete
hide_output	yiimp coin NANAS delete
hide_output	yiimp coin SEEDS delete
hide_output	yiimp coin OPTION delete
hide_output	yiimp coin DRA delete
hide_output	yiimp coin GLUCK delete
hide_output	yiimp coin EXB delete
hide_output	yiimp coin GREED delete
hide_output	yiimp coin MOIN delete
hide_output	yiimp coin Vcoin  delete
hide_output	yiimp coin TWLV delete
hide_output	yiimp coin RDN delete
hide_output	yiimp coin PSY delete
hide_output	yiimp coin ECC delete
hide_output	yiimp coin SNRG delete
hide_output	yiimp coin ADC delete
hide_output	yiimp coin CREVA delete
hide_output	yiimp coin VCN delete
hide_output	yiimp coin 32BIT delete
hide_output	yiimp coin XNA delete
hide_output	yiimp coin TWERK delete
hide_output	yiimp coin CS delete
hide_output	yiimp coin GENIUS delete
hide_output	yiimp coin PRE delete
hide_output	yiimp coin NICE delete
hide_output	yiimp coin CORG delete
hide_output	yiimp coin DB delete
hide_output	yiimp coin EQM delete
hide_output	yiimp coin FADE delete
hide_output	yiimp coin SED delete
hide_output	yiimp coin SKB delete
hide_output	yiimp coin TNG delete
hide_output	yiimp coin ARB delete
hide_output	yiimp coin DCC delete
hide_output	yiimp coin PTA delete
hide_output	yiimp coin MRB delete
hide_output	yiimp coin BTA delete
hide_output	yiimp coin GRT delete
hide_output	yiimp coin AST delete
hide_output	yiimp coin BA delete
hide_output	yiimp coin KRAK delete
hide_output	yiimp coin M1 delete
hide_output	yiimp coin 16BIT delete
hide_output	yiimp coin TB delete
hide_output	yiimp coin BIT16 delete
hide_output	yiimp coin CLV delete
hide_output	yiimp coin SHELL delete
hide_output	yiimp coin LIMX delete
hide_output	yiimp coin BTI delete
hide_output	yiimp coin FSN delete
hide_output	yiimp coin TKT delete
hide_output	yiimp coin FCS delete
hide_output	yiimp coin VTN delete
hide_output	yiimp coin EPC delete
hide_output	yiimp coin PKB delete
hide_output	yiimp coin GAM delete
hide_output	yiimp coin ISL delete
hide_output	yiimp coin VIRAL delete
hide_output	yiimp coin UTLE delete
hide_output	yiimp coin PNC delete
hide_output	yiimp coin GOAT delete
hide_output	yiimp coin EPY delete
hide_output	yiimp coin CTO delete
hide_output	yiimp coin SPC delete
hide_output	yiimp coin GRAV delete
hide_output	yiimp coin GPH delete
hide_output	yiimp coin UNIT delete
hide_output	yiimp coin BUB delete
hide_output	yiimp coin TDFB delete
hide_output	yiimp coin SPHR delete
hide_output	yiimp coin GUM delete
hide_output	yiimp coin XMS delete
hide_output	yiimp coin XSEED delete
hide_output	yiimp coin XNX delete
hide_output	yiimp coin XTP delete
hide_output	yiimp coin DOX delete
hide_output	yiimp coin QTZ delete
hide_output	yiimp coin UNAT-skein delete
hide_output	yiimp coin AIB delete
hide_output	yiimp coin GRAM delete
hide_output	yiimp coin SIGU delete
hide_output	yiimp coin BLITZ delete
hide_output	yiimp coin NIRO delete
hide_output	yiimp coin HUGE delete
hide_output	yiimp coin 7 delete
hide_output	yiimp coin DRZ delete
hide_output	yiimp coin UIS-qubit delete
hide_output	yiimp coin UIS-skein delete
hide_output	yiimp coin SLING delete
hide_output	yiimp coin COV delete
hide_output	yiimp coin NTRN delete
hide_output	yiimp coin CTK delete
hide_output	yiimp coin CF delete
hide_output	yiimp coin CGN delete
hide_output	yiimp coin OK delete
hide_output	yiimp coin 8BIT delete
hide_output	yiimp coin IEC delete
hide_output	yiimp coin P7C delete
hide_output	yiimp coin HZT delete
hide_output	yiimp coin LEA delete
hide_output	yiimp coin GIZ delete
hide_output	yiimp coin ETRUST delete
hide_output	yiimp coin XPRO delete
hide_output	yiimp coin TRON delete
hide_output	yiimp coin DECR delete
hide_output	yiimp coin RICE delete
hide_output	yiimp coin STP delete
hide_output	yiimp coin NXE delete
hide_output	yiimp coin AECC delete
hide_output	yiimp coin PLANET delete
hide_output	yiimp coin FIRE delete
hide_output	yiimp coin ANAL delete
hide_output	yiimp coin MTLMC3 delete
hide_output	yiimp coin TWIST delete
hide_output	yiimp coin CRIME delete
hide_output	yiimp coin BTCR delete
hide_output	yiimp coin TEC delete
hide_output	yiimp coin KARMA delete
hide_output	yiimp coin TCX delete
hide_output	yiimp coin TAB delete
hide_output	yiimp coin NDOGE delete
hide_output	yiimp coin GIFT delete
hide_output	yiimp coin BBCC delete
hide_output	yiimp coin TRICK delete
hide_output	yiimp coin DGMS delete
hide_output	yiimp coin CCB delete
hide_output	yiimp coin OZC delete
hide_output	yiimp coin STK delete
hide_output	yiimp coin SIC delete
hide_output	yiimp coin EGG delete
hide_output	yiimp coin EKN delete
hide_output	yiimp coin MRP delete
hide_output	yiimp coin QORA delete
hide_output	yiimp coin PXL delete
hide_output	yiimp coin CRY delete
hide_output	yiimp coin URC delete
hide_output	yiimp coin ICN delete
hide_output	yiimp coin OCTO delete
hide_output	yiimp coin EUR delete
hide_output	yiimp coin CAD delete
hide_output	yiimp coin CC delete
hide_output	yiimp coin XEM delete
hide_output	yiimp coin SLFI delete
hide_output	yiimp coin 256 delete
hide_output	yiimp coin ICASH delete
hide_output	yiimp coin BTCRY delete
hide_output	yiimp coin XDB delete
hide_output	yiimp coin ZIRK delete
hide_output	yiimp coin CRAVE delete
hide_output	yiimp coin BITZ delete
hide_output	yiimp coin OMC delete
hide_output	yiimp coin PAY delete
hide_output	yiimp coin LDOGE delete
hide_output	yiimp coin RBT delete
hide_output	yiimp coin ASN delete
hide_output	yiimp coin MINE delete
hide_output	yiimp coin XAU delete
hide_output	yiimp coin XFC delete
hide_output	yiimp coin UNC delete
hide_output	yiimp coin XCO delete
hide_output	yiimp coin VOYA delete
hide_output	yiimp coin XVC delete
hide_output	yiimp coin WBB delete
hide_output	yiimp coin ECASH delete
hide_output	yiimp coin MTR delete
hide_output	yiimp coin NSR delete
hide_output	yiimp coin GSM delete
hide_output	yiimp coin PTY delete
hide_output	yiimp coin LYB delete
hide_output	yiimp coin SUP delete
hide_output	yiimp coin CIN delete
hide_output	yiimp coin DD delete
hide_output	yiimp coin SMAC delete
hide_output	yiimp coin GRID delete
hide_output	yiimp coin SLM delete
hide_output	yiimp coin LTS delete
hide_output	yiimp coin XTC delete
hide_output	yiimp coin DGORE delete
hide_output	yiimp coin BITB delete
hide_output	yiimp coin BEAN delete
hide_output	yiimp coin PEN delete
hide_output	yiimp coin NVCD delete
hide_output	yiimp coin XPD delete
hide_output	yiimp coin CBX delete
hide_output	yiimp coin CELL delete
hide_output	yiimp coin KOBO delete
hide_output	yiimp coin LQD delete
hide_output	yiimp coin XTR delete
hide_output	yiimp coin 10K delete
hide_output	yiimp coin MYST delete
hide_output	yiimp coin BTCS delete
hide_output	yiimp coin XPB delete
hide_output	yiimp coin CETI delete
hide_output	yiimp coin OMA delete
hide_output	yiimp coin CCC delete
hide_output	yiimp coin XFB delete
hide_output	yiimp coin OBS delete
hide_output	yiimp coin SOON delete
hide_output	yiimp coin GIG delete
hide_output	yiimp coin XAP delete
hide_output	yiimp coin XBC delete
hide_output	yiimp coin XCH delete
hide_output	yiimp coin XCN delete
hide_output	yiimp coin XCP delete
hide_output	yiimp coin XDP delete
hide_output	yiimp coin XUSD delete
hide_output	yiimp coin YACC delete
hide_output	yiimp coin 1CR delete
hide_output	yiimp coin ACH delete
hide_output	yiimp coin ADN delete
hide_output	yiimp coin BCN delete
hide_output	yiimp coin BELA delete
hide_output	yiimp coin C2 delete
hide_output	yiimp coin CGA delete
hide_output	yiimp coin CHA delete
hide_output	yiimp coin CNMT delete
hide_output	yiimp coin CYC delete
hide_output	yiimp coin DIEM delete
hide_output	yiimp coin DSH delete
hide_output	yiimp coin FLDC delete
hide_output	yiimp coin GAP delete
hide_output	yiimp coin GDN delete
hide_output	yiimp coin GEMZ delete
hide_output	yiimp coin GOLD delete
hide_output	yiimp coin GRS delete
hide_output	yiimp coin HIRO delete
hide_output	yiimp coin HZ delete
hide_output	yiimp coin JLH delete
hide_output	yiimp coin LTBC delete
hide_output	yiimp coin MAID delete
hide_output	yiimp coin MCN delete
hide_output	yiimp coin MIL delete
hide_output	yiimp coin MMC delete
hide_output	yiimp coin MMNXT delete
hide_output	yiimp coin MNTA delete
hide_output	yiimp coin MRS delete
hide_output	yiimp coin NBT delete
hide_output	yiimp coin NOXT delete
hide_output	yiimp coin NXTI delete
hide_output	yiimp coin PIGGY delete
hide_output	yiimp coin PRC delete
hide_output	yiimp coin RIC delete
hide_output	yiimp coin SJCX delete
hide_output	yiimp coin SQL delete
hide_output	yiimp coin SRCC delete
hide_output	yiimp coin SWARM delete
hide_output	yiimp coin UNITY delete
hide_output	yiimp coin WOLF delete
hide_output	yiimp coin XWC delete
hide_output	yiimp coin FSC2 delete
hide_output	yiimp coin RBR delete
hide_output	yiimp coin CSD delete
hide_output	yiimp coin XDE delete
hide_output	yiimp coin XPC delete
hide_output	yiimp coin DGD delete
hide_output	yiimp coin ARI delete
hide_output	yiimp coin XBS delete
hide_output	yiimp coin USDT delete
hide_output	yiimp coin GP delete
hide_output	yiimp coin CON delete
hide_output	yiimp coin EAGS delete
hide_output	yiimp coin NKA delete
hide_output	yiimp coin INCA delete
hide_output	yiimp coin XSP delete
hide_output	yiimp coin BCR delete
hide_output	yiimp coin BLK delete
hide_output	yiimp coin SBIT delete
hide_output	yiimp coin UIS delete
hide_output	yiimp coin HGC delete
hide_output	yiimp coin 2015 delete
hide_output	yiimp coin GMC delete
hide_output	yiimp coin VMC delete
hide_output	yiimp coin ggggg delete
hide_output	yiimp coin UCI delete
hide_output	yiimp coin EQX delete
hide_output	yiimp coin TAK delete
hide_output	yiimp coin TEK delete
hide_output	yiimp coin TES delete
hide_output	yiimp coin TGC delete
hide_output	yiimp coin TOR delete
hide_output	yiimp coin TRC delete
hide_output	yiimp coin UNB delete
hide_output	yiimp coin USDe delete
hide_output	yiimp coin XCR delete
hide_output	yiimp coin XJO delete
hide_output	yiimp coin XLB delete
hide_output	yiimp coin YAC delete
hide_output	yiimp coin YBC delete
hide_output	yiimp coin ZCC delete
hide_output	yiimp coin ZED delete
hide_output	yiimp coin ADT delete
hide_output	yiimp coin ASC delete
hide_output	yiimp coin BAT delete
hide_output	yiimp coin COL delete
hide_output	yiimp coin CPR delete
hide_output	yiimp coin CTM delete
hide_output	yiimp coin DBL delete
hide_output	yiimp coin DMC delete
hide_output	yiimp coin ELP delete
hide_output	yiimp coin FLAP delete
hide_output	yiimp coin GME delete
hide_output	yiimp coin LEAF delete
hide_output	yiimp coin LOT delete
hide_output	yiimp coin MEM delete
hide_output	yiimp coin MEOW delete
hide_output	yiimp coin MST delete
hide_output	yiimp coin RBBT delete
hide_output	yiimp coin RED delete
hide_output	yiimp coin TIPS delete
hide_output	yiimp coin TIX delete
hide_output	yiimp coin XNC delete
hide_output	yiimp coin ZEIT delete
hide_output	yiimp coin AC delete
hide_output	yiimp coin Acoin  delete
hide_output	yiimp coin AGS delete
hide_output	yiimp coin ALF delete
hide_output	yiimp coin ALN delete
hide_output	yiimp coin AMC delete
hide_output	yiimp coin ARG delete
hide_output	yiimp coin AUR delete
hide_output	yiimp coin BCX delete
hide_output	yiimp coin BEN delete
hide_output	yiimp coin BET delete
hide_output	yiimp coin BNCR delete
hide_output	yiimp coin BOST delete
hide_output	yiimp coin BQC delete
hide_output	yiimp coin BTB delete
hide_output	yiimp coin BTE delete
hide_output	yiimp coin BTG delete
hide_output	yiimp coin BUK delete
hide_output	yiimp coin CACH delete
hide_output	yiimp coin CAP delete
hide_output	yiimp coin CASH delete
hide_output	yiimp coin CGB delete
hide_output	yiimp coin CINNI delete
hide_output	yiimp coin CMC delete
hide_output	yiimp coin CNC delete
hide_output	yiimp coin CNL delete
hide_output	yiimp coin COMM delete
hide_output	yiimp coin COOL delete
hide_output	yiimp coin CRACK delete
hide_output	yiimp coin CRC delete
hide_output	yiimp coin CSC delete
hide_output	yiimp coin DEM delete
hide_output	yiimp coin DMD delete
hide_output	yiimp coin DRKC delete
hide_output	yiimp coin DT delete
hide_output	yiimp coin DVC delete
hide_output	yiimp coin EAC delete
hide_output	yiimp coin ELC delete
hide_output	yiimp coin EMD delete
hide_output	yiimp coin EZC delete
hide_output	yiimp coin FFC delete
hide_output	yiimp coin FLT delete
hide_output	yiimp coin FRAC delete
hide_output	yiimp coin FRK delete
hide_output	yiimp coin FST delete
hide_output	yiimp coin GDC delete
hide_output	yiimp coin GLC delete
hide_output	yiimp coin GLD delete
hide_output	yiimp coin GLX delete
hide_output	yiimp coin GLYPH delete
hide_output	yiimp coin GUE delete
hide_output	yiimp coin HBN delete
hide_output	yiimp coin HVC delete
hide_output	yiimp coin ICB delete
hide_output	yiimp coin IXC delete
hide_output	yiimp coin JKC delete
hide_output	yiimp coin KDC delete
hide_output	yiimp coin KGC delete
hide_output	yiimp coin LAB delete
hide_output	yiimp coin LGD delete
hide_output	yiimp coin LK7 delete
hide_output	yiimp coin LKY delete
hide_output	yiimp coin LTB delete
hide_output	yiimp coin LTCX delete
hide_output	yiimp coin LYC delete
hide_output	yiimp coin MED delete
hide_output	yiimp coin MNC delete
hide_output	yiimp coin MZC delete
hide_output	yiimp coin NAN delete
hide_output	yiimp coin NBL delete
hide_output	yiimp coin NEC delete
hide_output	yiimp coin NRB delete
hide_output	yiimp coin NRS delete
hide_output	yiimp coin NYAN delete
hide_output	yiimp coin OSC delete
hide_output	yiimp coin PHS delete
hide_output	yiimp coin Points delete
hide_output	yiimp coin PSEUD delete
hide_output	yiimp coin PTS delete
hide_output	yiimp coin PYC delete
hide_output	yiimp coin RT2 delete
hide_output	yiimp coin RYC delete
hide_output	yiimp coin SAT2 delete
hide_output	yiimp coin SBC delete
hide_output	yiimp coin SHLD delete
hide_output	yiimp coin SILK delete
hide_output	yiimp coin SMC delete
hide_output	yiimp coin SOLE delete
hide_output	yiimp coin SPA delete
hide_output	yiimp coin SPT delete
hide_output	yiimp coin SSV delete
hide_output	yiimp coin EMC2 delete
hide_output	yiimp coin GIMP delete
hide_output	yiimp coin GRC delete
hide_output	yiimp coin KRYP delete
hide_output	yiimp coin MIC delete
hide_output	yiimp coin MOTO delete
hide_output	yiimp coin MSC delete
hide_output	yiimp coin NIC delete
hide_output	yiimp coin NWO delete
hide_output	yiimp coin PLCN delete
hide_output	yiimp coin PROZ delete
hide_output	yiimp coin SONG delete
hide_output	yiimp coin SPUDS delete
hide_output	yiimp coin SQC delete
hide_output	yiimp coin VOXP delete
hide_output	yiimp coin VTX delete
hide_output	yiimp coin XRC delete
hide_output	yiimp coin XSX delete
hide_output	yiimp coin XVG delete
hide_output	yiimp coin DON delete
hide_output	yiimp coin FJC delete
hide_output	yiimp coin GCN delete
hide_output	yiimp coin GRN delete
hide_output	yiimp coin GUA delete
hide_output	yiimp coin HAM delete
hide_output	yiimp coin HEX delete
hide_output	yiimp coin IFC delete
hide_output	yiimp coin IRL delete
hide_output	yiimp coin KARM delete
hide_output	yiimp coin MINT delete
hide_output	yiimp coin MOON delete
hide_output	yiimp coin MTLMC delete
hide_output	yiimp coin NMC delete
hide_output	yiimp coin NYC delete
hide_output	yiimp coin ORB delete
hide_output	yiimp coin PCC delete
hide_output	yiimp coin PHC delete
hide_output	yiimp coin RC delete
hide_output	yiimp coin SXC delete
hide_output	yiimp coin TRL delete
hide_output	yiimp coin USD delete
hide_output	yiimp coin VTA delete
hide_output	yiimp coin XPM delete
hide_output	yiimp coin BURST delete
hide_output	yiimp coin LTCD delete
hide_output	yiimp coin CRAIG delete
hide_output	yiimp coin TIT delete
hide_output	yiimp coin BSTY delete
hide_output	yiimp coin GNS delete
hide_output	yiimp coin DCN delete
hide_output	yiimp coin PXI delete
hide_output	yiimp coin ROS delete
hide_output	yiimp coin STV delete
hide_output	yiimp coin OPAL delete
hide_output	yiimp coin EXCL delete
hide_output	yiimp coin PYRA delete
hide_output	yiimp coin NET delete
hide_output	yiimp coin SEED delete
hide_output	yiimp coin PND delete
hide_output	yiimp coin GHC delete
hide_output	yiimp coin DOPE delete
hide_output	yiimp coin ONE delete
hide_output	yiimp coin BLEU delete
hide_output	yiimp coin BVC delete
hide_output	yiimp coin CAGE delete
hide_output	yiimp coin CDN delete
hide_output	yiimp coin CESC delete
hide_output	yiimp coin CLR delete
hide_output	yiimp coin CZC delete
hide_output	yiimp coin CHILD delete
hide_output	yiimp coin XQN delete
hide_output	yiimp coin RDD delete
hide_output	yiimp coin NXT delete
hide_output	yiimp coin BC delete
hide_output	yiimp coin MYR-qubit delete
hide_output	yiimp coin UTC delete
hide_output	yiimp coin 888 delete
hide_output	yiimp coin EFL delete
hide_output	yiimp coin DIME delete
hide_output	yiimp coin SLR delete
hide_output	yiimp coin WATER delete
hide_output	yiimp coin NLG delete
hide_output	yiimp coin GIVE delete
hide_output	yiimp coin WC delete
hide_output	yiimp coin NOBL delete
hide_output	yiimp coin BITS delete
hide_output	yiimp coin BLU delete
hide_output	yiimp coin OC delete
hide_output	yiimp coin THC delete
hide_output	yiimp coin ENRG delete
hide_output	yiimp coin SHIBE delete
hide_output	yiimp coin SFR delete
hide_output	yiimp coin NAUT delete
hide_output	yiimp coin VRC delete
hide_output	yiimp coin CURE delete
hide_output	yiimp coin SYNC delete
hide_output	yiimp coin BLC delete
hide_output	yiimp coin XSI delete
hide_output	yiimp coin XC delete
hide_output	yiimp coin XDQ delete
hide_output	yiimp coin MMXIV delete
hide_output	yiimp coin CAIX delete
hide_output	yiimp coin BBR delete
hide_output	yiimp coin HYPER delete
hide_output	yiimp coin CCN delete
hide_output	yiimp coin KTK delete
hide_output	yiimp coin MUGA delete
hide_output	yiimp coin VOOT delete
hide_output	yiimp coin BN delete
hide_output	yiimp coin XMR delete
hide_output	yiimp coin CLOAK delete
hide_output	yiimp coin CHCC delete
hide_output	yiimp coin BURN delete
hide_output	yiimp coin KORE delete
hide_output	yiimp coin RZR delete
hide_output	yiimp coin XDN delete
hide_output	yiimp coin MIN delete
hide_output	yiimp coin TECH delete
hide_output	yiimp coin GML delete
hide_output	yiimp coin TRK delete
hide_output	yiimp coin WKC delete
hide_output	yiimp coin QTL delete
hide_output	yiimp coin XXX delete
hide_output	yiimp coin AERO delete
hide_output	yiimp coin TRUST delete
hide_output	yiimp coin BRIT delete
hide_output	yiimp coin JUDGE delete
hide_output	yiimp coin NAV delete
hide_output	yiimp coin XST delete
hide_output	yiimp coin APEX delete
hide_output	yiimp coin ZET delete
hide_output	yiimp coin BTCD delete
hide_output	yiimp coin KEY delete
hide_output	yiimp coin NUD delete
hide_output	yiimp coin TRI delete
hide_output	yiimp coin PES delete
hide_output	yiimp coin ICG delete
hide_output	yiimp coin UNO delete
hide_output	yiimp coin ESC delete
hide_output	yiimp coin PINK delete
hide_output	yiimp coin IOC delete
hide_output	yiimp coin SDC delete
hide_output	yiimp coin RAW delete
hide_output	yiimp coin MAX delete
hide_output	yiimp coin LXC delete
hide_output	yiimp coin BOOM delete
hide_output	yiimp coin BOB delete
hide_output	yiimp coin UNAT delete
hide_output	yiimp coin MWC delete
hide_output	yiimp coin VAULT delete
hide_output	yiimp coin FC2 delete
hide_output	yiimp coin SSD delete
hide_output	yiimp coin BIG delete
hide_output	yiimp coin GB delete
hide_output	yiimp coin ROOT delete
hide_output	yiimp coin AXR delete
hide_output	yiimp coin RIPO delete
hide_output	yiimp coin FIBRE delete
hide_output	yiimp coin SHADE delete
hide_output	yiimp coin FLEX delete
hide_output	yiimp coin XBOT delete
hide_output	yiimp coin XCASH delete
hide_output	yiimp coin NKT delete
hide_output	yiimp coin TTC delete
hide_output	yiimp coin CLAM delete
hide_output	yiimp coin VTR delete
hide_output	yiimp coin SUPER delete
hide_output	yiimp coin NOO delete
hide_output	yiimp coin XPY delete
hide_output	yiimp coin SMLY delete
hide_output	yiimp coin BCENT delete
hide_output	yiimp coin DS delete
hide_output	yiimp coin FAIR delete
hide_output	yiimp coin EVENT delete
hide_output	yiimp coin HUC delete
hide_output	yiimp coin CAT delete
hide_output	yiimp coin WDC delete
hide_output	yiimp coin BTM delete
hide_output	yiimp coin RMS delete
hide_output	yiimp coin ANC delete
hide_output	yiimp coin MEC delete
hide_output	yiimp coin MONA delete
hide_output	yiimp coin DGC delete
hide_output	yiimp coin BCF delete
hide_output	yiimp coin SYS delete
hide_output	yiimp coin ULTC delete
hide_output	yiimp coin CXC delete
hide_output	yiimp coin METAL delete
hide_output	yiimp coin SPR delete
hide_output	yiimp coin CBR delete
hide_output	yiimp coin FIND delete
hide_output	yiimp coin AM delete
hide_output	yiimp coin FUD delete
hide_output	yiimp coin ERM delete
hide_output	yiimp coin VIA delete
hide_output	yiimp coin CKC delete
hide_output	yiimp coin BTS delete
hide_output	yiimp coin DEAF delete
hide_output	yiimp coin HIC delete
hide_output	yiimp coin BAY delete
hide_output	yiimp coin VIOR delete
hide_output	yiimp coin VPN delete
hide_output	yiimp coin MN delete
hide_output	yiimp coin EXE delete
hide_output	yiimp coin PFC delete
hide_output	yiimp coin GSX delete
hide_output	yiimp coin BRXv2 delete
hide_output	yiimp coin ACHK delete
hide_output	yiimp coin CRYPT delete
hide_output	yiimp coin HLC delete
hide_output	yiimp coin SWIFT delete
hide_output	yiimp coin ARCH delete
hide_output	yiimp coin GAIA delete
hide_output	yiimp coin WWC delete
hide_output	yiimp coin XRP delete
hide_output	yiimp coin LMR delete
hide_output	yiimp coin MNE delete
hide_output	yiimp coin CRW delete
hide_output	yiimp coin VDO delete
hide_output	yiimp coin NOPE delete
hide_output	yiimp coin XWT delete
hide_output	yiimp coin DTC delete
hide_output	yiimp coin SMBR delete
hide_output	yiimp coin HYP delete
hide_output	yiimp coin QBK delete
hide_output	yiimp coin CENT delete
hide_output	yiimp coin BLOCK delete
hide_output	yiimp coin CATC delete
hide_output	yiimp coin SCSY delete
hide_output	yiimp coin ABY delete
hide_output	yiimp coin BALLS delete
hide_output	yiimp coin QSLV delete
hide_output	yiimp coin U delete
hide_output	yiimp coin BYC delete
hide_output	yiimp coin BUN delete
hide_output	yiimp coin ZER delete
hide_output	yiimp coin ZNY delete
hide_output	yiimp coin MRY delete
hide_output	yiimp coin CANN delete
hide_output	yiimp coin POT delete
hide_output	yiimp coin TAG delete
hide_output	yiimp coin RBY delete
hide_output	yiimp coin NOTE delete
hide_output	yiimp coin LTC delete
hide_output	yiimp coin NVC delete
hide_output	yiimp coin 42 delete
hide_output	yiimp coin JBS delete
hide_output	yiimp coin LSD delete
hide_output	yiimp coin J delete
hide_output	yiimp coin SLG delete
hide_output	yiimp coin VIK delete
hide_output	yiimp coin RPC delete
hide_output	yiimp coin XG delete
hide_output	yiimp coin DP delete
hide_output	yiimp coin MARYJ delete
hide_output	yiimp coin XMG delete
hide_output	yiimp coin RUBLE delete
hide_output	yiimp coin XCLD delete
hide_output	yiimp coin BST delete
hide_output	yiimp coin HNC delete
hide_output	yiimp coin GXG delete
hide_output	yiimp coin BTX delete
hide_output	yiimp coin 007 delete
hide_output	yiimp coin LUX delete
hide_output	yiimp coin ACP delete
hide_output	yiimp coin STR delete
hide_output	yiimp coin PAC delete
hide_output	yiimp coin PPC delete
hide_output	yiimp coin MLS delete
hide_output	yiimp coin FLO delete
hide_output	yiimp coin PTC delete
hide_output	yiimp coin GUN delete
hide_output	yiimp coin DOGE delete
echo "Junk coin removal completed. Type motd to verify screens are running."

# Prevents error when trying to log in to admin panel the first time...

sudo touch $STORAGE_ROOT/yiimp/site/log/debug.log
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/.
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/debug.log

# Delete me no longer needed after it runs the first time

sudo rm -r $STORAGE_ROOT/yiimp/first_boot.sh
cd $HOME/multipool/yiimp_single
