#####################################################
# Created by cryptopool.builders for crypto use...
#####################################################

source /etc/functions.sh
source $STORAGE_ROOT/yiimp/.yiimp.conf
cd $HOME/multipool/yiimp_single

echo -e " Installing cron screens to crontab...$COL_RESET"
(crontab -l 2>/dev/null; echo "@reboot sleep 20 && /home/crypto-data/yiimp/starts/screens.start.sh") | crontab -
if [[ ("$CoinPort" == "no") ]]; then
(crontab -l 2>/dev/null; echo "@reboot sleep 20 && /home/crypto-data/yiimp/starts/stratum.start.sh") | crontab -
fi
(crontab -l 2>/dev/null; echo "@reboot source /etc/functions.sh") | crontab -
(crontab -l 2>/dev/null; echo "@reboot source /etc/multipool.conf") | crontab -
sudo cp -r first_boot.sh $STORAGE_ROOT/yiimp/
echo -e "$GREEN Crontab system complete...$COL_RESET"

echo -e " Creating YiiMP Screens startup script...$COL_RESET"

echo '#!/usr/bin/env bash
source /etc/multipool.conf
# Ugly way to remove junk coins from initial YiiMP database on first boot
source $STORAGE_ROOT/yiimp/.yiimp.conf
if [[ ! -e '$STORAGE_ROOT/yiimp/first_boot.sh' ]]; then
echo
else
source $STORAGE_ROOT/yiimp/first_boot.sh
fi
################################################################################
# Author: cryptopool.builders
#
#
# Program: yiimp screen startup script
#
# BTC Donation: 12Pt3vQhQpXvyzBd5qcoL17ouhNFyihyz5
#
################################################################################
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/.
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/debug.log
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
CRONS=$STORAGE_ROOT/yiimp/site/crons
screen -dmS main bash $CRONS/main.sh
screen -dmS loop2 bash $CRONS/loop2.sh
screen -dmS blocks bash $CRONS/blocks.sh
screen -dmS debug tail -f $LOG_DIR/debug.log
' | sudo -E tee $STORAGE_ROOT/yiimp/starts/screens.start.sh >/dev/null 2>&1
sudo chmod +x $STORAGE_ROOT/yiimp/starts/screens.start.sh

echo -e " Creating Stratum screens start script...$COL_RESET"

echo '#!/usr/bin/env bash
################################################################################
# Author: cryptopool.builders
#
#
# Program: yiimp stratum startup script
#
# BTC Donation: 12Pt3vQhQpXvyzBd5qcoL17ouhNFyihyz5
#
################################################################################
source /etc/multipool.conf
source $STORAGE_ROOT/yiimp/.yiimp.conf
STRATUM_DIR=$STORAGE_ROOT/yiimp/site/stratum
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
screen -dmS c11 bash $STRATUM_DIR/run.sh c11
screen -dmS deep bash $STRATUM_DIR/run.sh deep
screen -dmS x11 bash $STRATUM_DIR/run.sh x11
screen -dmS 2x11evo bash $STRATUM_DIR/run.sh x11evo
screen -dmS x13 bash $STRATUM_DIR/run.sh x13
screen -dmS x14 bash bash $STRATUM_DIR/run.sh x14
screen -dmS x15 bash $STRATUM_DIR/run.sh x15
screen -dmS x17 bash $STRATUM_DIR/run.sh x17
screen -dmS xevan bash $STRATUM_DIR/run.sh xevan
screen -dmS timetravel bash $STRATUM_DIR/run.sh timetravel
screen -dmS bitcore bash $STRATUM_DIR/run.sh bitcore
screen -dmS hmq1725 bash $STRATUM_DIR/run.sh hmq1725
screen -dmS tribus bash $STRATUM_DIR/run.sh tribus
screen -dmS sha bash $STRATUM_DIR/run.sh sha
screen -dmS 2sha256t bash $STRATUM_DIR/run.sh sha256t
screen -dmS scrypt bash $STRATUM_DIR/run.sh scrypt
screen -dmS 2scryptn bash $STRATUM_DIR/run.sh scryptn
screen -dmS luffa bash $STRATUM_DIR/run.sh luffa
screen -dmS neo bash $STRATUM_DIR/run.sh neo
screen -dmS nist5 bash $STRATUM_DIR/run.sh nist5
screen -dmS penta bash $STRATUM_DIR/run.sh penta
screen -dmS quark bash $STRATUM_DIR/run.sh quark
screen -dmS qubit bash $STRATUM_DIR/run.sh qubit
screen -dmS jha bash $STRATUM_DIR/run.sh jha
screen -dmS dmd-gr bash $STRATUM_DIR/run.sh dmd-gr
screen -dmS myr-gr bash $STRATUM_DIR/run.sh myr-gr
screen -dmS lbry bash $STRATUM_DIR/run.sh lbry
screen -dmS lyra2 bash $STRATUM_DIR/run.sh lyra2
screen -dmS 2lyra2v2 bash $STRATUM_DIR/run.sh lyra2v2
screen -dmS zero bash $STRATUM_DIR/run.sh lyra2z
screen -dmS blakecoin bash $STRATUM_DIR/run.sh blakecoin # blake 8
screen -dmS blake bash $STRATUM_DIR/run.sh blake
screen -dmS 2blake2s bash $STRATUM_DIR/run.sh blake2s
screen -dmS vanilla bash $STRATUM_DIR/run.sh vanilla # blake 8
screen -dmS decred bash $STRATUM_DIR/run.sh decred # blake 14
screen -dmS keccak bash $STRATUM_DIR/run.sh keccak
screen -dmS whirlpool bash $STRATUM_DIR/run.sh whirlpool
screen -dmS skein bash $STRATUM_DIR/run.sh skein
screen -dmS 2skein2 bash $STRATUM_DIR/run.sh skein2
screen -dmS yescrypt bash $STRATUM_DIR/run.sh yescrypt
screen -dmS zr5 bash $STRATUM_DIR/run.sh zr5
screen -dmS sib bash $STRATUM_DIR/run.sh sib
screen -dmS m7m sudo bash $STRATUM_DIR/run.sh m7m
screen -dmS veltor bash $STRATUM_DIR/run.sh veltor
screen -dmS velvet bash $STRATUM_DIR/run.sh velvet
screen -dmS argon2 bash $STRATUM_DIR/run.sh argon2
screen -dmS groestl bash $STRATUM_DIR/run.sh groestl
screen -dmS skunk bash $STRATUM_DIR/run.sh skunk
screen -dmS phi1612 bash $STRATUM_DIR/run.sh phi1612
screen -dmS hsr bash $STRATUM_DIR/run.sh hsr
screen -dmS yescryptr16 bash $STRATUM_DIR/run.sh yescryptR16
screen -dmS x16r bash $STRATUM_DIR/run.sh x16r
' | sudo -E tee $STORAGE_ROOT/yiimp/starts/stratum.start.sh >/dev/null 2>&1
sudo chmod +x $STORAGE_ROOT/yiimp/starts/stratum.start.sh

echo '
source /etc/multipool.conf
source $STORAGE_ROOT/yiimp/.yiimp.conf
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
CRONS=$STORAGE_ROOT/yiimp/site/crons
STRATUM_DIR=$STORAGE_ROOT/yiimp/site/stratum
' | sudo -E tee $STORAGE_ROOT/yiimp/.prescreens.start.conf >/dev/null 2>&1

echo "source /etc/multipool.conf" | hide_output tee -a ~/.bashrc
echo "source $STORAGE_ROOT/yiimp/.prescreens.start.conf" | hide_output tee -a ~/.bashrc
echo -e "$GREEN YiiMP Screens added...$COL_RESET"

echo -e "Removing junk coins from YiiMP Database, this may take several minutes...$COL_RESET"
 sudo sg yiimpadmin "yiimp coin MDT delete"
 sudo sg yiimpadmin "yiimp coin FLAX delete"
 sudo sg yiimpadmin "yiimp coin CHC delete"
 sudo sg yiimpadmin "yiimp coin DRP delete"
 sudo sg yiimpadmin "yiimp coin VTC delete"
 sudo sg yiimpadmin "yiimp coin FTC delete"
 sudo sg yiimpadmin "yiimp coin UFO delete"
 sudo sg yiimpadmin "yiimp coin PXC delete"
 sudo sg yiimpadmin "yiimp coin HAL delete"
 sudo sg yiimpadmin "yiimp coin XAI delete"
 sudo sg yiimpadmin "yiimp coin QRK delete"
 sudo sg yiimpadmin "yiimp coin MUE delete"
 sudo sg yiimpadmin "yiimp coin BOD delete"
 sudo sg yiimpadmin "yiimp coin SRC delete"
 sudo sg yiimpadmin "yiimp coin BTQ delete"
 sudo sg yiimpadmin "yiimp coin GEO delete"
 sudo sg yiimpadmin "yiimp coin DGB delete"
 sudo sg yiimpadmin "yiimp coin CYP delete"
 sudo sg yiimpadmin "yiimp coin IDC delete"
 sudo sg yiimpadmin "yiimp coin NEOS delete"
 sudo sg yiimpadmin "yiimp coin MYR delete"
 sudo sg yiimpadmin "yiimp coin XDC delete"
 sudo sg yiimpadmin "yiimp coin SKC delete"
 sudo sg yiimpadmin "yiimp coin LOG delete"
 sudo sg yiimpadmin "yiimp coin ILM delete"
 sudo sg yiimpadmin "yiimp coin START delete"
 sudo sg yiimpadmin "yiimp coin URO delete"
 sudo sg yiimpadmin "yiimp coin DASH delete"
 sudo sg yiimpadmin "yiimp coin BSC delete"
 sudo sg yiimpadmin "yiimp coin HEDG delete"
 sudo sg yiimpadmin "yiimp coin AMBER delete"
 sudo sg yiimpadmin "yiimp coin HTML5 delete"
 sudo sg yiimpadmin "yiimp coin ZRC delete"
 sudo sg yiimpadmin "yiimp coin UNF delete"
 sudo sg yiimpadmin "yiimp coin DES delete"
 sudo sg yiimpadmin "yiimp coin KUMA delete"
 sudo sg yiimpadmin "yiimp coin MEME delete"
 sudo sg yiimpadmin "yiimp coin FOOT delete"
 sudo sg yiimpadmin "yiimp coin UMO delete"
 sudo sg yiimpadmin "yiimp coin G3N delete"
 sudo sg yiimpadmin "yiimp coin SHND delete"
 sudo sg yiimpadmin "yiimp coin WHIPPED delete"
 sudo sg yiimpadmin "yiimp coin FLY delete"
 sudo sg yiimpadmin "yiimp coin BUMBA delete"
 sudo sg yiimpadmin "yiimp coin EBG delete"
 sudo sg yiimpadmin "yiimp coin I0C delete"
 sudo sg yiimpadmin "yiimp coin CAPT delete"
 sudo sg yiimpadmin "yiimp coin PAK delete"
 sudo sg yiimpadmin "yiimp coin EUC delete"
 sudo sg yiimpadmin "yiimp coin GRE-OLD delete"
 sudo sg yiimpadmin "yiimp coin PR delete"
 sudo sg yiimpadmin "yiimp coin VGC delete"
 sudo sg yiimpadmin "yiimp coin CFC delete"
 sudo sg yiimpadmin "yiimp coin GAME delete"
 sudo sg yiimpadmin "yiimp coin FONZ delete"
 sudo sg yiimpadmin "yiimp coin DBIC delete"
 sudo sg yiimpadmin "yiimp coin TRUMP delete"
 sudo sg yiimpadmin "yiimp coin JIF delete"
 sudo sg yiimpadmin "yiimp coin EVIL delete"
 sudo sg yiimpadmin "yiimp coin EVO delete"
 sudo sg yiimpadmin "yiimp coin LTCR delete"
 sudo sg yiimpadmin "yiimp coin SANDG delete"
 sudo sg yiimpadmin "yiimp coin RICHX delete"
 sudo sg yiimpadmin "yiimp coin ADZ delete"
 sudo sg yiimpadmin "yiimp coin DGCS delete"
 sudo sg yiimpadmin "yiimp coin BOLI delete"
 sudo sg yiimpadmin "yiimp coin LGBTQ delete"
 sudo sg yiimpadmin "yiimp coin ZOOM delete"
 sudo sg yiimpadmin "yiimp coin YOC delete"
 sudo sg yiimpadmin "yiimp coin SIB delete"
 sudo sg yiimpadmin "yiimp coin OPES delete"
 sudo sg yiimpadmin "yiimp coin NKC delete"
 sudo sg yiimpadmin "yiimp coin MMXVI delete"
 sudo sg yiimpadmin "yiimp coin MBL delete"
 sudo sg yiimpadmin "yiimp coin KNC delete"
 sudo sg yiimpadmin "yiimp coin AR2 delete"
 sudo sg yiimpadmin "yiimp coin AND delete"
 sudo sg yiimpadmin "yiimp coin TROLL delete"
 sudo sg yiimpadmin "yiimp coin DNET delete"
 sudo sg yiimpadmin "yiimp coin DCR delete"
 sudo sg yiimpadmin "yiimp coin EGC delete"
 sudo sg yiimpadmin "yiimp coin MND delete"
 sudo sg yiimpadmin "yiimp coin BNT delete"
 sudo sg yiimpadmin "yiimp coin AMS delete"
 sudo sg yiimpadmin "yiimp coin INFX delete"
 sudo sg yiimpadmin "yiimp coin BSD delete"
 sudo sg yiimpadmin "yiimp coin HTC delete"
 sudo sg yiimpadmin "yiimp coin CZECO delete"
 sudo sg yiimpadmin "yiimp coin EDRC delete"
 sudo sg yiimpadmin "yiimp coin FTP delete"
 sudo sg yiimpadmin "yiimp coin OP delete"
 sudo sg yiimpadmin "yiimp coin CHAI delete"
 sudo sg yiimpadmin "yiimp coin REV delete"
 sudo sg yiimpadmin "yiimp coin PULSE delete"
 sudo sg yiimpadmin "yiimp coin XCT delete"
 sudo sg yiimpadmin "yiimp coin STS delete"
 sudo sg yiimpadmin "yiimp coin EC delete"
 sudo sg yiimpadmin "yiimp coin CYG delete"
 sudo sg yiimpadmin "yiimp coin VAL delete"
 sudo sg yiimpadmin "yiimp coin TBC delete"
 sudo sg yiimpadmin "yiimp coin CRBIT delete"
 sudo sg yiimpadmin "yiimp coin GMX delete"
 sudo sg yiimpadmin "yiimp coin HODL delete"
 sudo sg yiimpadmin "yiimp coin KLC delete"
 sudo sg yiimpadmin "yiimp coin BUZZ delete"
 sudo sg yiimpadmin "yiimp coin ADCN delete"
 sudo sg yiimpadmin "yiimp coin RBIES delete"
 sudo sg yiimpadmin "yiimp coin SEC delete"
 sudo sg yiimpadmin "yiimp coin XID delete"
 sudo sg yiimpadmin "yiimp coin BTCU delete"
 sudo sg yiimpadmin "yiimp coin WARP delete"
 sudo sg yiimpadmin "yiimp coin CPNC delete"
 sudo sg yiimpadmin "yiimp coin HIRE delete"
 sudo sg yiimpadmin "yiimp coin SLS delete"
 sudo sg yiimpadmin "yiimp coin XHI delete"
 sudo sg yiimpadmin "yiimp coin RADS delete"
 sudo sg yiimpadmin "yiimp coin BTP delete"
 sudo sg yiimpadmin "yiimp coin X2 delete"
 sudo sg yiimpadmin "yiimp coin HMP delete"
 sudo sg yiimpadmin "yiimp coin BRONZ delete"
 sudo sg yiimpadmin "yiimp coin RUBIT delete"
 sudo sg yiimpadmin "yiimp coin REP delete"
 sudo sg yiimpadmin "yiimp coin SPL delete"
 sudo sg yiimpadmin "yiimp coin CIONZ delete"
 sudo sg yiimpadmin "yiimp coin SCRT delete"
 sudo sg yiimpadmin "yiimp coin DEUR delete"
 sudo sg yiimpadmin "yiimp coin VOX delete"
 sudo sg yiimpadmin "yiimp coin CLUB delete"
 sudo sg yiimpadmin "yiimp coin SCOT delete"
 sudo sg yiimpadmin "yiimp coin FLOZ delete"
 sudo sg yiimpadmin "yiimp coin STATS delete"
 sudo sg yiimpadmin "yiimp coin HZDOGE delete"
 sudo sg yiimpadmin "yiimp coin WLC delete"
 sudo sg yiimpadmin "yiimp coin BITUSD delete"
 sudo sg yiimpadmin "yiimp coin BITCNY delete"
 sudo sg yiimpadmin "yiimp coin FNX delete"
 sudo sg yiimpadmin "yiimp coin APC delete"
 sudo sg yiimpadmin "yiimp coin XLM delete"
 sudo sg yiimpadmin "yiimp coin AGRS delete"
 sudo sg yiimpadmin "yiimp coin DROP delete"
 sudo sg yiimpadmin "yiimp coin AMP delete"
 sudo sg yiimpadmin "yiimp coin ANTI delete"
 sudo sg yiimpadmin "yiimp coin 1337 delete"
 sudo sg yiimpadmin "yiimp coin TRBO delete"
 sudo sg yiimpadmin "yiimp coin BIC delete"
 sudo sg yiimpadmin "yiimp coin SOIL delete"
 sudo sg yiimpadmin "yiimp coin OMNI delete"
 sudo sg yiimpadmin "yiimp coin CUBE delete"
 sudo sg yiimpadmin "yiimp coin BAC delete"
 sudo sg yiimpadmin "yiimp coin WOP delete"
 sudo sg yiimpadmin "yiimp coin FCT delete"
 sudo sg yiimpadmin "yiimp coin PRT delete"
 sudo sg yiimpadmin "yiimp coin CBIT delete"
 sudo sg yiimpadmin "yiimp coin NEU delete"
 sudo sg yiimpadmin "yiimp coin STEPS delete"
 sudo sg yiimpadmin "yiimp coin EXP delete"
 sudo sg yiimpadmin "yiimp coin BCY delete"
 sudo sg yiimpadmin "yiimp coin PRIME delete"
 sudo sg yiimpadmin "yiimp coin SHF delete"
 sudo sg yiimpadmin "yiimp coin SWING delete"
 sudo sg yiimpadmin "yiimp coin MI delete"
 sudo sg yiimpadmin "yiimp coin MACRO delete"
 sudo sg yiimpadmin "yiimp coin SC delete"
 sudo sg yiimpadmin "yiimp coin GCR delete"
 sudo sg yiimpadmin "yiimp coin MAPC delete"
 sudo sg yiimpadmin "yiimp coin GCC delete"
 sudo sg yiimpadmin "yiimp coin TX delete"
 sudo sg yiimpadmin "yiimp coin ETH delete"
 sudo sg yiimpadmin "yiimp coin CRE delete"
 sudo sg yiimpadmin "yiimp coin AEON delete"
 sudo sg yiimpadmin "yiimp coin GSY delete"
 sudo sg yiimpadmin "yiimp coin CHIP delete"
 sudo sg yiimpadmin "yiimp coin BTCHC delete"
 sudo sg yiimpadmin "yiimp coin AXIOM delete"
 sudo sg yiimpadmin "yiimp coin FUEL delete"
 sudo sg yiimpadmin "yiimp coin BIOS delete"
 sudo sg yiimpadmin "yiimp coin CPC delete"
 sudo sg yiimpadmin "yiimp coin IBITS delete"
 sudo sg yiimpadmin "yiimp coin DIGS delete"
 sudo sg yiimpadmin "yiimp coin NOC delete"
 sudo sg yiimpadmin "yiimp coin MCZ delete"
 sudo sg yiimpadmin "yiimp coin BANX delete"
 sudo sg yiimpadmin "yiimp coin CPN delete"
 sudo sg yiimpadmin "yiimp coin SPRTS delete"
 sudo sg yiimpadmin "yiimp coin SPROUT delete"
 sudo sg yiimpadmin "yiimp coin NUKE delete"
 sudo sg yiimpadmin "yiimp coin 2BACCO delete"
 sudo sg yiimpadmin "yiimp coin FIC delete"
 sudo sg yiimpadmin "yiimp coin LFO delete"
 sudo sg yiimpadmin "yiimp coin VERSA delete"
 sudo sg yiimpadmin "yiimp coin MCAR delete"
 sudo sg yiimpadmin "yiimp coin CARB delete"
 sudo sg yiimpadmin "yiimp coin ZUR delete"
 sudo sg yiimpadmin "yiimp coin VAPE delete"
 sudo sg yiimpadmin "yiimp coin TALK delete"
 sudo sg yiimpadmin "yiimp coin RUM delete"
 sudo sg yiimpadmin "yiimp coin PPCD delete"
 sudo sg yiimpadmin "yiimp coin PHO delete"
 sudo sg yiimpadmin "yiimp coin P0001 delete"
 sudo sg yiimpadmin "yiimp coin NODE delete"
 sudo sg yiimpadmin "yiimp coin MRC delete"
 sudo sg yiimpadmin "yiimp coin ISO delete"
 sudo sg yiimpadmin "yiimp coin HANSA delete"
 sudo sg yiimpadmin "yiimp coin FX01 delete"
 sudo sg yiimpadmin "yiimp coin FRSH delete"
 sudo sg yiimpadmin "yiimp coin FIMK delete"
 sudo sg yiimpadmin "yiimp coin FAIL delete"
 sudo sg yiimpadmin "yiimp coin DRM delete"
 sudo sg yiimpadmin "yiimp coin DRK delete"
 sudo sg yiimpadmin "yiimp coin CV2 delete"
 sudo sg yiimpadmin "yiimp coin BTRHA delete"
 sudo sg yiimpadmin "yiimp coin ALCUREX delete"
 sudo sg yiimpadmin "yiimp coin BNX delete"
 sudo sg yiimpadmin "yiimp coin QUIT delete"
 sudo sg yiimpadmin "yiimp coin V delete"
 sudo sg yiimpadmin "yiimp coin PLC delete"
 sudo sg yiimpadmin "yiimp coin GRW delete"
 sudo sg yiimpadmin "yiimp coin DUO delete"
 sudo sg yiimpadmin "yiimp coin ANI delete"
 sudo sg yiimpadmin "yiimp coin CDC delete"
 sudo sg yiimpadmin "yiimp coin CX delete"
 sudo sg yiimpadmin "yiimp coin MARS delete"
 sudo sg yiimpadmin "yiimp coin SHA delete"
 sudo sg yiimpadmin "yiimp coin FETISH delete"
 sudo sg yiimpadmin "yiimp coin EXC delete"
 sudo sg yiimpadmin "yiimp coin BDSM delete"
 sudo sg yiimpadmin "yiimp coin OFF delete"
 sudo sg yiimpadmin "yiimp coin EMC delete"
 sudo sg yiimpadmin "yiimp coin BLZ delete"
 sudo sg yiimpadmin "yiimp coin CHAO delete"
 sudo sg yiimpadmin "yiimp coin CNO delete"
 sudo sg yiimpadmin "yiimp coin FUNK delete"
 sudo sg yiimpadmin "yiimp coin UNIC delete"
 sudo sg yiimpadmin "yiimp coin DUCK delete"
 sudo sg yiimpadmin "yiimp coin BSY delete"
 sudo sg yiimpadmin "yiimp coin SPN delete"
 sudo sg yiimpadmin "yiimp coin IPC delete"
 sudo sg yiimpadmin "yiimp coin '"'$MINEZ'"' delete"
 sudo sg yiimpadmin "yiimp coin '"'$MINEW'"' delete"
 sudo sg yiimpadmin "yiimp coin ADD delete"
 sudo sg yiimpadmin "yiimp coin '"'$MINE'"' delete"
 sudo sg yiimpadmin "yiimp coin FTCC delete"
 sudo sg yiimpadmin "yiimp coin CIV delete"
 sudo sg yiimpadmin "yiimp coin TOP delete"
 sudo sg yiimpadmin "yiimp coin TTY delete"
 sudo sg yiimpadmin "yiimp coin NTC delete"
 sudo sg yiimpadmin "yiimp coin KIWI delete"
 sudo sg yiimpadmin "yiimp coin XPL delete"
 sudo sg yiimpadmin "yiimp coin XGR delete"
 sudo sg yiimpadmin "yiimp coin '"'$$$'"' delete"
 sudo sg yiimpadmin "yiimp coin 66 delete"
 sudo sg yiimpadmin "yiimp coin MDC delete"
 sudo sg yiimpadmin "yiimp coin SVC delete"
 sudo sg yiimpadmin "yiimp coin DARK delete"
 sudo sg yiimpadmin "yiimp coin POP delete"
 sudo sg yiimpadmin "yiimp coin WSX delete"
 sudo sg yiimpadmin "yiimp coin DOT delete"
 sudo sg yiimpadmin "yiimp coin YOVI delete"
 sudo sg yiimpadmin "yiimp coin HXX delete"
 sudo sg yiimpadmin "yiimp coin CRPS delete"
 sudo sg yiimpadmin "yiimp coin BAM delete"
 sudo sg yiimpadmin "yiimp coin SJW delete"
 sudo sg yiimpadmin "yiimp coin GMCX delete"
 sudo sg yiimpadmin "yiimp coin SPX delete"
 sudo sg yiimpadmin "yiimp coin EXT delete"
 sudo sg yiimpadmin "yiimp coin TENNET delete"
 sudo sg yiimpadmin "yiimp coin KC delete"
 sudo sg yiimpadmin "yiimp coin BLUS delete"
 sudo sg yiimpadmin "yiimp coin XRA delete"
 sudo sg yiimpadmin "yiimp coin SPEC delete"
 sudo sg yiimpadmin "yiimp coin EA delete"
 sudo sg yiimpadmin "yiimp coin TAGR delete"
 sudo sg yiimpadmin "yiimp coin HAZE delete"
 sudo sg yiimpadmin "yiimp coin TAM delete"
 sudo sg yiimpadmin "yiimp coin POLY delete"
 sudo sg yiimpadmin "yiimp coin INDEX delete"
 sudo sg yiimpadmin "yiimp coin GENI delete"
 sudo sg yiimpadmin "yiimp coin BUCKS delete"
 sudo sg yiimpadmin "yiimp coin SPKTR delete"
 sudo sg yiimpadmin "yiimp coin GENE delete"
 sudo sg yiimpadmin "yiimp coin GRM delete"
 sudo sg yiimpadmin "yiimp coin DIBS delete"
 sudo sg yiimpadmin "yiimp coin GTFO delete"
 sudo sg yiimpadmin "yiimp coin FUTC delete"
 sudo sg yiimpadmin "yiimp coin XVI delete"
 sudo sg yiimpadmin "yiimp coin GLOBE delete"
 sudo sg yiimpadmin "yiimp coin SMSR delete"
 sudo sg yiimpadmin "yiimp coin CIRC delete"
 sudo sg yiimpadmin "yiimp coin WOC2 delete"
 sudo sg yiimpadmin "yiimp coin NODX delete"
 sudo sg yiimpadmin "yiimp coin ERC delete"
 sudo sg yiimpadmin "yiimp coin SEN delete"
 sudo sg yiimpadmin "yiimp coin SAK delete"
 sudo sg yiimpadmin "yiimp coin EOC delete"
 sudo sg yiimpadmin "yiimp coin TRANSF delete"
 sudo sg yiimpadmin "yiimp coin GEN delete"
 sudo sg yiimpadmin "yiimp coin DRKT delete"
 sudo sg yiimpadmin "yiimp coin XCE delete"
 sudo sg yiimpadmin "yiimp coin XPH delete"
 sudo sg yiimpadmin "yiimp coin FIST delete"
 sudo sg yiimpadmin "yiimp coin DUB delete"
 sudo sg yiimpadmin "yiimp coin VAPOR delete"
 sudo sg yiimpadmin "yiimp coin ARPA delete"
 sudo sg yiimpadmin "yiimp coin BNB delete"
 sudo sg yiimpadmin "yiimp coin NANAS delete"
 sudo sg yiimpadmin "yiimp coin SEEDS delete"
 sudo sg yiimpadmin "yiimp coin OPTION delete"
 sudo sg yiimpadmin "yiimp coin DRA delete"
 sudo sg yiimpadmin "yiimp coin GLUCK delete"
 sudo sg yiimpadmin "yiimp coin EXB delete"
 sudo sg yiimpadmin "yiimp coin GREED delete"
 sudo sg yiimpadmin "yiimp coin MOIN delete"
 sudo sg yiimpadmin "yiimp coin Vcoin  delete"
 sudo sg yiimpadmin "yiimp coin TWLV delete"
 sudo sg yiimpadmin "yiimp coin RDN delete"
 sudo sg yiimpadmin "yiimp coin PSY delete"
 sudo sg yiimpadmin "yiimp coin ECC delete"
 sudo sg yiimpadmin "yiimp coin SNRG delete"
 sudo sg yiimpadmin "yiimp coin ADC delete"
 sudo sg yiimpadmin "yiimp coin CREVA delete"
 sudo sg yiimpadmin "yiimp coin VCN delete"
 sudo sg yiimpadmin "yiimp coin 32BIT delete"
 sudo sg yiimpadmin "yiimp coin XNA delete"
 sudo sg yiimpadmin "yiimp coin TWERK delete"
 sudo sg yiimpadmin "yiimp coin CS delete"
 sudo sg yiimpadmin "yiimp coin GENIUS delete"
 sudo sg yiimpadmin "yiimp coin PRE delete"
 sudo sg yiimpadmin "yiimp coin NICE delete"
 sudo sg yiimpadmin "yiimp coin CORG delete"
 sudo sg yiimpadmin "yiimp coin DB delete"
 sudo sg yiimpadmin "yiimp coin EQM delete"
 sudo sg yiimpadmin "yiimp coin FADE delete"
 sudo sg yiimpadmin "yiimp coin SED delete"
 sudo sg yiimpadmin "yiimp coin SKB delete"
 sudo sg yiimpadmin "yiimp coin TNG delete"
 sudo sg yiimpadmin "yiimp coin ARB delete"
 sudo sg yiimpadmin "yiimp coin DCC delete"
 sudo sg yiimpadmin "yiimp coin PTA delete"
 sudo sg yiimpadmin "yiimp coin MRB delete"
 sudo sg yiimpadmin "yiimp coin BTA delete"
 sudo sg yiimpadmin "yiimp coin GRT delete"
 sudo sg yiimpadmin "yiimp coin AST delete"
 sudo sg yiimpadmin "yiimp coin BA delete"
 sudo sg yiimpadmin "yiimp coin KRAK delete"
 sudo sg yiimpadmin "yiimp coin M1 delete"
 sudo sg yiimpadmin "yiimp coin 16BIT delete"
 sudo sg yiimpadmin "yiimp coin TB delete"
 sudo sg yiimpadmin "yiimp coin BIT16 delete"
 sudo sg yiimpadmin "yiimp coin CLV delete"
 sudo sg yiimpadmin "yiimp coin SHELL delete"
 sudo sg yiimpadmin "yiimp coin LIMX delete"
 sudo sg yiimpadmin "yiimp coin BTI delete"
 sudo sg yiimpadmin "yiimp coin FSN delete"
 sudo sg yiimpadmin "yiimp coin TKT delete"
 sudo sg yiimpadmin "yiimp coin FCS delete"
 sudo sg yiimpadmin "yiimp coin VTN delete"
 sudo sg yiimpadmin "yiimp coin EPC delete"
 sudo sg yiimpadmin "yiimp coin PKB delete"
 sudo sg yiimpadmin "yiimp coin GAM delete"
 sudo sg yiimpadmin "yiimp coin ISL delete"
 sudo sg yiimpadmin "yiimp coin VIRAL delete"
 sudo sg yiimpadmin "yiimp coin UTLE delete"
 sudo sg yiimpadmin "yiimp coin PNC delete"
 sudo sg yiimpadmin "yiimp coin GOAT delete"
 sudo sg yiimpadmin "yiimp coin EPY delete"
 sudo sg yiimpadmin "yiimp coin CTO delete"
 sudo sg yiimpadmin "yiimp coin SPC delete"
 sudo sg yiimpadmin "yiimp coin GRAV delete"
 sudo sg yiimpadmin "yiimp coin GPH delete"
 sudo sg yiimpadmin "yiimp coin UNIT delete"
 sudo sg yiimpadmin "yiimp coin BUB delete"
 sudo sg yiimpadmin "yiimp coin TDFB delete"
 sudo sg yiimpadmin "yiimp coin SPHR delete"
 sudo sg yiimpadmin "yiimp coin GUM delete"
 sudo sg yiimpadmin "yiimp coin XMS delete"
 sudo sg yiimpadmin "yiimp coin XSEED delete"
 sudo sg yiimpadmin "yiimp coin XNX delete"
 sudo sg yiimpadmin "yiimp coin XTP delete"
 sudo sg yiimpadmin "yiimp coin DOX delete"
 sudo sg yiimpadmin "yiimp coin QTZ delete"
 sudo sg yiimpadmin "yiimp coin UNAT-skein delete"
 sudo sg yiimpadmin "yiimp coin AIB delete"
 sudo sg yiimpadmin "yiimp coin GRAM delete"
 sudo sg yiimpadmin "yiimp coin SIGU delete"
 sudo sg yiimpadmin "yiimp coin BLITZ delete"
 sudo sg yiimpadmin "yiimp coin NIRO delete"
 sudo sg yiimpadmin "yiimp coin HUGE delete"
 sudo sg yiimpadmin "yiimp coin 7 delete"
 sudo sg yiimpadmin "yiimp coin DRZ delete"
 sudo sg yiimpadmin "yiimp coin UIS-qubit delete"
 sudo sg yiimpadmin "yiimp coin UIS-skein delete"
 sudo sg yiimpadmin "yiimp coin SLING delete"
 sudo sg yiimpadmin "yiimp coin COV delete"
 sudo sg yiimpadmin "yiimp coin NTRN delete"
 sudo sg yiimpadmin "yiimp coin CTK delete"
 sudo sg yiimpadmin "yiimp coin CF delete"
 sudo sg yiimpadmin "yiimp coin CGN delete"
 sudo sg yiimpadmin "yiimp coin OK delete"
 sudo sg yiimpadmin "yiimp coin 8BIT delete"
 sudo sg yiimpadmin "yiimp coin IEC delete"
 sudo sg yiimpadmin "yiimp coin P7C delete"
 sudo sg yiimpadmin "yiimp coin HZT delete"
 sudo sg yiimpadmin "yiimp coin LEA delete"
 sudo sg yiimpadmin "yiimp coin GIZ delete"
 sudo sg yiimpadmin "yiimp coin ETRUST delete"
 sudo sg yiimpadmin "yiimp coin XPRO delete"
 sudo sg yiimpadmin "yiimp coin TRON delete"
 sudo sg yiimpadmin "yiimp coin DECR delete"
 sudo sg yiimpadmin "yiimp coin RICE delete"
 sudo sg yiimpadmin "yiimp coin STP delete"
 sudo sg yiimpadmin "yiimp coin NXE delete"
 sudo sg yiimpadmin "yiimp coin AECC delete"
 sudo sg yiimpadmin "yiimp coin PLANET delete"
 sudo sg yiimpadmin "yiimp coin FIRE delete"
 sudo sg yiimpadmin "yiimp coin ANAL delete"
 sudo sg yiimpadmin "yiimp coin MTLMC3 delete"
 sudo sg yiimpadmin "yiimp coin TWIST delete"
 sudo sg yiimpadmin "yiimp coin CRIME delete"
 sudo sg yiimpadmin "yiimp coin BTCR delete"
 sudo sg yiimpadmin "yiimp coin TEC delete"
 sudo sg yiimpadmin "yiimp coin KARMA delete"
 sudo sg yiimpadmin "yiimp coin TCX delete"
 sudo sg yiimpadmin "yiimp coin TAB delete"
 sudo sg yiimpadmin "yiimp coin NDOGE delete"
 sudo sg yiimpadmin "yiimp coin GIFT delete"
 sudo sg yiimpadmin "yiimp coin BBCC delete"
 sudo sg yiimpadmin "yiimp coin TRICK delete"
 sudo sg yiimpadmin "yiimp coin DGMS delete"
 sudo sg yiimpadmin "yiimp coin CCB delete"
 sudo sg yiimpadmin "yiimp coin OZC delete"
 sudo sg yiimpadmin "yiimp coin STK delete"
 sudo sg yiimpadmin "yiimp coin SIC delete"
 sudo sg yiimpadmin "yiimp coin EGG delete"
 sudo sg yiimpadmin "yiimp coin EKN delete"
 sudo sg yiimpadmin "yiimp coin MRP delete"
 sudo sg yiimpadmin "yiimp coin QORA delete"
 sudo sg yiimpadmin "yiimp coin PXL delete"
 sudo sg yiimpadmin "yiimp coin CRY delete"
 sudo sg yiimpadmin "yiimp coin URC delete"
 sudo sg yiimpadmin "yiimp coin ICN delete"
 sudo sg yiimpadmin "yiimp coin OCTO delete"
 sudo sg yiimpadmin "yiimp coin EUR delete"
 sudo sg yiimpadmin "yiimp coin CAD delete"
 sudo sg yiimpadmin "yiimp coin CC delete"
 sudo sg yiimpadmin "yiimp coin XEM delete"
 sudo sg yiimpadmin "yiimp coin SLFI delete"
 sudo sg yiimpadmin "yiimp coin 256 delete"
 sudo sg yiimpadmin "yiimp coin ICASH delete"
 sudo sg yiimpadmin "yiimp coin BTCRY delete"
 sudo sg yiimpadmin "yiimp coin XDB delete"
 sudo sg yiimpadmin "yiimp coin ZIRK delete"
 sudo sg yiimpadmin "yiimp coin CRAVE delete"
 sudo sg yiimpadmin "yiimp coin BITZ delete"
 sudo sg yiimpadmin "yiimp coin OMC delete"
 sudo sg yiimpadmin "yiimp coin PAY delete"
 sudo sg yiimpadmin "yiimp coin LDOGE delete"
 sudo sg yiimpadmin "yiimp coin RBT delete"
 sudo sg yiimpadmin "yiimp coin ASN delete"
 sudo sg yiimpadmin "yiimp coin MINE delete"
 sudo sg yiimpadmin "yiimp coin XAU delete"
 sudo sg yiimpadmin "yiimp coin XFC delete"
 sudo sg yiimpadmin "yiimp coin UNC delete"
 sudo sg yiimpadmin "yiimp coin XCO delete"
 sudo sg yiimpadmin "yiimp coin VOYA delete"
 sudo sg yiimpadmin "yiimp coin XVC delete"
 sudo sg yiimpadmin "yiimp coin WBB delete"
 sudo sg yiimpadmin "yiimp coin ECASH delete"
 sudo sg yiimpadmin "yiimp coin MTR delete"
 sudo sg yiimpadmin "yiimp coin NSR delete"
 sudo sg yiimpadmin "yiimp coin GSM delete"
 sudo sg yiimpadmin "yiimp coin PTY delete"
 sudo sg yiimpadmin "yiimp coin LYB delete"
 sudo sg yiimpadmin "yiimp coin SUP delete"
 sudo sg yiimpadmin "yiimp coin CIN delete"
 sudo sg yiimpadmin "yiimp coin DD delete"
 sudo sg yiimpadmin "yiimp coin SMAC delete"
 sudo sg yiimpadmin "yiimp coin GRID delete"
 sudo sg yiimpadmin "yiimp coin SLM delete"
 sudo sg yiimpadmin "yiimp coin LTS delete"
 sudo sg yiimpadmin "yiimp coin XTC delete"
 sudo sg yiimpadmin "yiimp coin DGORE delete"
 sudo sg yiimpadmin "yiimp coin BITB delete"
 sudo sg yiimpadmin "yiimp coin BEAN delete"
 sudo sg yiimpadmin "yiimp coin PEN delete"
 sudo sg yiimpadmin "yiimp coin NVCD delete"
 sudo sg yiimpadmin "yiimp coin XPD delete"
 sudo sg yiimpadmin "yiimp coin CBX delete"
 sudo sg yiimpadmin "yiimp coin CELL delete"
 sudo sg yiimpadmin "yiimp coin KOBO delete"
 sudo sg yiimpadmin "yiimp coin LQD delete"
 sudo sg yiimpadmin "yiimp coin XTR delete"
 sudo sg yiimpadmin "yiimp coin 10K delete"
 sudo sg yiimpadmin "yiimp coin MYST delete"
 sudo sg yiimpadmin "yiimp coin BTCS delete"
 sudo sg yiimpadmin "yiimp coin XPB delete"
 sudo sg yiimpadmin "yiimp coin CETI delete"
 sudo sg yiimpadmin "yiimp coin OMA delete"
 sudo sg yiimpadmin "yiimp coin CCC delete"
 sudo sg yiimpadmin "yiimp coin XFB delete"
 sudo sg yiimpadmin "yiimp coin OBS delete"
 sudo sg yiimpadmin "yiimp coin SOON delete"
 sudo sg yiimpadmin "yiimp coin GIG delete"
 sudo sg yiimpadmin "yiimp coin XAP delete"
 sudo sg yiimpadmin "yiimp coin XBC delete"
 sudo sg yiimpadmin "yiimp coin XCH delete"
 sudo sg yiimpadmin "yiimp coin XCN delete"
 sudo sg yiimpadmin "yiimp coin XCP delete"
 sudo sg yiimpadmin "yiimp coin XDP delete"
 sudo sg yiimpadmin "yiimp coin XUSD delete"
 sudo sg yiimpadmin "yiimp coin YACC delete"
 sudo sg yiimpadmin "yiimp coin 1CR delete"
 sudo sg yiimpadmin "yiimp coin ACH delete"
 sudo sg yiimpadmin "yiimp coin ADN delete"
 sudo sg yiimpadmin "yiimp coin BCN delete"
 sudo sg yiimpadmin "yiimp coin BELA delete"
 sudo sg yiimpadmin "yiimp coin C2 delete"
 sudo sg yiimpadmin "yiimp coin CGA delete"
 sudo sg yiimpadmin "yiimp coin CHA delete"
 sudo sg yiimpadmin "yiimp coin CNMT delete"
 sudo sg yiimpadmin "yiimp coin CYC delete"
 sudo sg yiimpadmin "yiimp coin DIEM delete"
 sudo sg yiimpadmin "yiimp coin DSH delete"
 sudo sg yiimpadmin "yiimp coin FLDC delete"
 sudo sg yiimpadmin "yiimp coin GAP delete"
 sudo sg yiimpadmin "yiimp coin GDN delete"
 sudo sg yiimpadmin "yiimp coin GEMZ delete"
 sudo sg yiimpadmin "yiimp coin GOLD delete"
 sudo sg yiimpadmin "yiimp coin GRS delete"
 sudo sg yiimpadmin "yiimp coin HIRO delete"
 sudo sg yiimpadmin "yiimp coin HZ delete"
 sudo sg yiimpadmin "yiimp coin JLH delete"
 sudo sg yiimpadmin "yiimp coin LTBC delete"
 sudo sg yiimpadmin "yiimp coin MAID delete"
 sudo sg yiimpadmin "yiimp coin MCN delete"
 sudo sg yiimpadmin "yiimp coin MIL delete"
 sudo sg yiimpadmin "yiimp coin MMC delete"
 sudo sg yiimpadmin "yiimp coin MMNXT delete"
 sudo sg yiimpadmin "yiimp coin MNTA delete"
 sudo sg yiimpadmin "yiimp coin MRS delete"
 sudo sg yiimpadmin "yiimp coin NBT delete"
 sudo sg yiimpadmin "yiimp coin NOXT delete"
 sudo sg yiimpadmin "yiimp coin NXTI delete"
 sudo sg yiimpadmin "yiimp coin PIGGY delete"
 sudo sg yiimpadmin "yiimp coin PRC delete"
 sudo sg yiimpadmin "yiimp coin RIC delete"
 sudo sg yiimpadmin "yiimp coin SJCX delete"
 sudo sg yiimpadmin "yiimp coin SQL delete"
 sudo sg yiimpadmin "yiimp coin SRCC delete"
 sudo sg yiimpadmin "yiimp coin SWARM delete"
 sudo sg yiimpadmin "yiimp coin UNITY delete"
 sudo sg yiimpadmin "yiimp coin WOLF delete"
 sudo sg yiimpadmin "yiimp coin XWC delete"
 sudo sg yiimpadmin "yiimp coin FSC2 delete"
 sudo sg yiimpadmin "yiimp coin RBR delete"
 sudo sg yiimpadmin "yiimp coin CSD delete"
 sudo sg yiimpadmin "yiimp coin XDE delete"
 sudo sg yiimpadmin "yiimp coin XPC delete"
 sudo sg yiimpadmin "yiimp coin DGD delete"
 sudo sg yiimpadmin "yiimp coin ARI delete"
 sudo sg yiimpadmin "yiimp coin XBS delete"
 sudo sg yiimpadmin "yiimp coin USDT delete"
 sudo sg yiimpadmin "yiimp coin GP delete"
 sudo sg yiimpadmin "yiimp coin CON delete"
 sudo sg yiimpadmin "yiimp coin EAGS delete"
 sudo sg yiimpadmin "yiimp coin NKA delete"
 sudo sg yiimpadmin "yiimp coin INCA delete"
 sudo sg yiimpadmin "yiimp coin XSP delete"
 sudo sg yiimpadmin "yiimp coin BCR delete"
 sudo sg yiimpadmin "yiimp coin BLK delete"
 sudo sg yiimpadmin "yiimp coin SBIT delete"
 sudo sg yiimpadmin "yiimp coin UIS delete"
 sudo sg yiimpadmin "yiimp coin HGC delete"
 sudo sg yiimpadmin "yiimp coin 2015 delete"
 sudo sg yiimpadmin "yiimp coin GMC delete"
 sudo sg yiimpadmin "yiimp coin VMC delete"
 sudo sg yiimpadmin "yiimp coin ggggg delete"
 sudo sg yiimpadmin "yiimp coin UCI delete"
 sudo sg yiimpadmin "yiimp coin EQX delete"
 sudo sg yiimpadmin "yiimp coin TAK delete"
 sudo sg yiimpadmin "yiimp coin TEK delete"
 sudo sg yiimpadmin "yiimp coin TES delete"
 sudo sg yiimpadmin "yiimp coin TGC delete"
 sudo sg yiimpadmin "yiimp coin TOR delete"
 sudo sg yiimpadmin "yiimp coin TRC delete"
 sudo sg yiimpadmin "yiimp coin UNB delete"
 sudo sg yiimpadmin "yiimp coin USDe delete"
 sudo sg yiimpadmin "yiimp coin XCR delete"
 sudo sg yiimpadmin "yiimp coin XJO delete"
 sudo sg yiimpadmin "yiimp coin XLB delete"
 sudo sg yiimpadmin "yiimp coin YAC delete"
 sudo sg yiimpadmin "yiimp coin YBC delete"
 sudo sg yiimpadmin "yiimp coin ZCC delete"
 sudo sg yiimpadmin "yiimp coin ZED delete"
 sudo sg yiimpadmin "yiimp coin ADT delete"
 sudo sg yiimpadmin "yiimp coin ASC delete"
 sudo sg yiimpadmin "yiimp coin BAT delete"
 sudo sg yiimpadmin "yiimp coin COL delete"
 sudo sg yiimpadmin "yiimp coin CPR delete"
 sudo sg yiimpadmin "yiimp coin CTM delete"
 sudo sg yiimpadmin "yiimp coin DBL delete"
 sudo sg yiimpadmin "yiimp coin DMC delete"
 sudo sg yiimpadmin "yiimp coin ELP delete"
 sudo sg yiimpadmin "yiimp coin FLAP delete"
 sudo sg yiimpadmin "yiimp coin GME delete"
 sudo sg yiimpadmin "yiimp coin LEAF delete"
 sudo sg yiimpadmin "yiimp coin LOT delete"
 sudo sg yiimpadmin "yiimp coin MEM delete"
 sudo sg yiimpadmin "yiimp coin MEOW delete"
 sudo sg yiimpadmin "yiimp coin MST delete"
 sudo sg yiimpadmin "yiimp coin RBBT delete"
 sudo sg yiimpadmin "yiimp coin RED delete"
 sudo sg yiimpadmin "yiimp coin TIPS delete"
 sudo sg yiimpadmin "yiimp coin TIX delete"
 sudo sg yiimpadmin "yiimp coin XNC delete"
 sudo sg yiimpadmin "yiimp coin ZEIT delete"
 sudo sg yiimpadmin "yiimp coin AC delete"
 sudo sg yiimpadmin "yiimp coin Acoin  delete"
 sudo sg yiimpadmin "yiimp coin AGS delete"
 sudo sg yiimpadmin "yiimp coin ALF delete"
 sudo sg yiimpadmin "yiimp coin ALN delete"
 sudo sg yiimpadmin "yiimp coin AMC delete"
 sudo sg yiimpadmin "yiimp coin ARG delete"
 sudo sg yiimpadmin "yiimp coin AUR delete"
 sudo sg yiimpadmin "yiimp coin BCX delete"
 sudo sg yiimpadmin "yiimp coin BEN delete"
 sudo sg yiimpadmin "yiimp coin BET delete"
 sudo sg yiimpadmin "yiimp coin BNCR delete"
 sudo sg yiimpadmin "yiimp coin BOST delete"
 sudo sg yiimpadmin "yiimp coin BQC delete"
 sudo sg yiimpadmin "yiimp coin BTB delete"
 sudo sg yiimpadmin "yiimp coin BTE delete"
 sudo sg yiimpadmin "yiimp coin BTG delete"
 sudo sg yiimpadmin "yiimp coin BUK delete"
 sudo sg yiimpadmin "yiimp coin CACH delete"
 sudo sg yiimpadmin "yiimp coin CAP delete"
 sudo sg yiimpadmin "yiimp coin CASH delete"
 sudo sg yiimpadmin "yiimp coin CGB delete"
 sudo sg yiimpadmin "yiimp coin CINNI delete"
 sudo sg yiimpadmin "yiimp coin CMC delete"
 sudo sg yiimpadmin "yiimp coin CNC delete"
 sudo sg yiimpadmin "yiimp coin CNL delete"
 sudo sg yiimpadmin "yiimp coin COMM delete"
 sudo sg yiimpadmin "yiimp coin COOL delete"
 sudo sg yiimpadmin "yiimp coin CRACK delete"
 sudo sg yiimpadmin "yiimp coin CRC delete"
 sudo sg yiimpadmin "yiimp coin CSC delete"
 sudo sg yiimpadmin "yiimp coin DEM delete"
 sudo sg yiimpadmin "yiimp coin DMD delete"
 sudo sg yiimpadmin "yiimp coin DRKC delete"
 sudo sg yiimpadmin "yiimp coin DT delete"
 sudo sg yiimpadmin "yiimp coin DVC delete"
 sudo sg yiimpadmin "yiimp coin EAC delete"
 sudo sg yiimpadmin "yiimp coin ELC delete"
 sudo sg yiimpadmin "yiimp coin EMD delete"
 sudo sg yiimpadmin "yiimp coin EZC delete"
 sudo sg yiimpadmin "yiimp coin FFC delete"
 sudo sg yiimpadmin "yiimp coin FLT delete"
 sudo sg yiimpadmin "yiimp coin FRAC delete"
 sudo sg yiimpadmin "yiimp coin FRK delete"
 sudo sg yiimpadmin "yiimp coin FST delete"
 sudo sg yiimpadmin "yiimp coin GDC delete"
 sudo sg yiimpadmin "yiimp coin GLC delete"
 sudo sg yiimpadmin "yiimp coin GLD delete"
 sudo sg yiimpadmin "yiimp coin GLX delete"
 sudo sg yiimpadmin "yiimp coin GLYPH delete"
 sudo sg yiimpadmin "yiimp coin GUE delete"
 sudo sg yiimpadmin "yiimp coin HBN delete"
 sudo sg yiimpadmin "yiimp coin HVC delete"
 sudo sg yiimpadmin "yiimp coin ICB delete"
 sudo sg yiimpadmin "yiimp coin IXC delete"
 sudo sg yiimpadmin "yiimp coin JKC delete"
 sudo sg yiimpadmin "yiimp coin KDC delete"
 sudo sg yiimpadmin "yiimp coin KGC delete"
 sudo sg yiimpadmin "yiimp coin LAB delete"
 sudo sg yiimpadmin "yiimp coin LGD delete"
 sudo sg yiimpadmin "yiimp coin LK7 delete"
 sudo sg yiimpadmin "yiimp coin LKY delete"
 sudo sg yiimpadmin "yiimp coin LTB delete"
 sudo sg yiimpadmin "yiimp coin LTCX delete"
 sudo sg yiimpadmin "yiimp coin LYC delete"
 sudo sg yiimpadmin "yiimp coin MED delete"
 sudo sg yiimpadmin "yiimp coin MNC delete"
 sudo sg yiimpadmin "yiimp coin MZC delete"
 sudo sg yiimpadmin "yiimp coin NAN delete"
 sudo sg yiimpadmin "yiimp coin NBL delete"
 sudo sg yiimpadmin "yiimp coin NEC delete"
 sudo sg yiimpadmin "yiimp coin NRB delete"
 sudo sg yiimpadmin "yiimp coin NRS delete"
 sudo sg yiimpadmin "yiimp coin NYAN delete"
 sudo sg yiimpadmin "yiimp coin OSC delete"
 sudo sg yiimpadmin "yiimp coin PHS delete"
 sudo sg yiimpadmin "yiimp coin Points delete"
 sudo sg yiimpadmin "yiimp coin PSEUD delete"
 sudo sg yiimpadmin "yiimp coin PTS delete"
 sudo sg yiimpadmin "yiimp coin PYC delete"
 sudo sg yiimpadmin "yiimp coin RT2 delete"
 sudo sg yiimpadmin "yiimp coin RYC delete"
 sudo sg yiimpadmin "yiimp coin SAT2 delete"
 sudo sg yiimpadmin "yiimp coin SBC delete"
 sudo sg yiimpadmin "yiimp coin SHLD delete"
 sudo sg yiimpadmin "yiimp coin SILK delete"
 sudo sg yiimpadmin "yiimp coin SMC delete"
 sudo sg yiimpadmin "yiimp coin SOLE delete"
 sudo sg yiimpadmin "yiimp coin SPA delete"
 sudo sg yiimpadmin "yiimp coin SPT delete"
 sudo sg yiimpadmin "yiimp coin SSV delete"
 sudo sg yiimpadmin "yiimp coin EMC2 delete"
 sudo sg yiimpadmin "yiimp coin GIMP delete"
 sudo sg yiimpadmin "yiimp coin GRC delete"
 sudo sg yiimpadmin "yiimp coin KRYP delete"
 sudo sg yiimpadmin "yiimp coin MIC delete"
 sudo sg yiimpadmin "yiimp coin MOTO delete"
 sudo sg yiimpadmin "yiimp coin MSC delete"
 sudo sg yiimpadmin "yiimp coin NIC delete"
 sudo sg yiimpadmin "yiimp coin NWO delete"
 sudo sg yiimpadmin "yiimp coin PLCN delete"
 sudo sg yiimpadmin "yiimp coin PROZ delete"
 sudo sg yiimpadmin "yiimp coin SONG delete"
 sudo sg yiimpadmin "yiimp coin SPUDS delete"
 sudo sg yiimpadmin "yiimp coin SQC delete"
 sudo sg yiimpadmin "yiimp coin VOXP delete"
 sudo sg yiimpadmin "yiimp coin VTX delete"
 sudo sg yiimpadmin "yiimp coin XRC delete"
 sudo sg yiimpadmin "yiimp coin XSX delete"
 sudo sg yiimpadmin "yiimp coin XVG delete"
 sudo sg yiimpadmin "yiimp coin DON delete"
 sudo sg yiimpadmin "yiimp coin FJC delete"
 sudo sg yiimpadmin "yiimp coin GCN delete"
 sudo sg yiimpadmin "yiimp coin GRN delete"
 sudo sg yiimpadmin "yiimp coin GUA delete"
 sudo sg yiimpadmin "yiimp coin HAM delete"
 sudo sg yiimpadmin "yiimp coin HEX delete"
 sudo sg yiimpadmin "yiimp coin IFC delete"
 sudo sg yiimpadmin "yiimp coin IRL delete"
 sudo sg yiimpadmin "yiimp coin KARM delete"
 sudo sg yiimpadmin "yiimp coin MINT delete"
 sudo sg yiimpadmin "yiimp coin MOON delete"
 sudo sg yiimpadmin "yiimp coin MTLMC delete"
 sudo sg yiimpadmin "yiimp coin NMC delete"
 sudo sg yiimpadmin "yiimp coin NYC delete"
 sudo sg yiimpadmin "yiimp coin ORB delete"
 sudo sg yiimpadmin "yiimp coin PCC delete"
 sudo sg yiimpadmin "yiimp coin PHC delete"
 sudo sg yiimpadmin "yiimp coin RC delete"
 sudo sg yiimpadmin "yiimp coin SXC delete"
 sudo sg yiimpadmin "yiimp coin TRL delete"
 sudo sg yiimpadmin "yiimp coin USD delete"
 sudo sg yiimpadmin "yiimp coin VTA delete"
 sudo sg yiimpadmin "yiimp coin XPM delete"
 sudo sg yiimpadmin "yiimp coin BURST delete"
 sudo sg yiimpadmin "yiimp coin LTCD delete"
 sudo sg yiimpadmin "yiimp coin CRAIG delete"
 sudo sg yiimpadmin "yiimp coin TIT delete"
 sudo sg yiimpadmin "yiimp coin BSTY delete"
 sudo sg yiimpadmin "yiimp coin GNS delete"
 sudo sg yiimpadmin "yiimp coin DCN delete"
 sudo sg yiimpadmin "yiimp coin PXI delete"
 sudo sg yiimpadmin "yiimp coin ROS delete"
 sudo sg yiimpadmin "yiimp coin STV delete"
 sudo sg yiimpadmin "yiimp coin OPAL delete"
 sudo sg yiimpadmin "yiimp coin EXCL delete"
 sudo sg yiimpadmin "yiimp coin PYRA delete"
 sudo sg yiimpadmin "yiimp coin NET delete"
 sudo sg yiimpadmin "yiimp coin SEED delete"
 sudo sg yiimpadmin "yiimp coin PND delete"
 sudo sg yiimpadmin "yiimp coin GHC delete"
 sudo sg yiimpadmin "yiimp coin DOPE delete"
 sudo sg yiimpadmin "yiimp coin ONE delete"
 sudo sg yiimpadmin "yiimp coin BLEU delete"
 sudo sg yiimpadmin "yiimp coin BVC delete"
 sudo sg yiimpadmin "yiimp coin CAGE delete"
 sudo sg yiimpadmin "yiimp coin CDN delete"
 sudo sg yiimpadmin "yiimp coin CESC delete"
 sudo sg yiimpadmin "yiimp coin CLR delete"
 sudo sg yiimpadmin "yiimp coin CZC delete"
 sudo sg yiimpadmin "yiimp coin CHILD delete"
 sudo sg yiimpadmin "yiimp coin XQN delete"
 sudo sg yiimpadmin "yiimp coin RDD delete"
 sudo sg yiimpadmin "yiimp coin NXT delete"
 sudo sg yiimpadmin "yiimp coin BC delete"
 sudo sg yiimpadmin "yiimp coin MYR-qubit delete"
 sudo sg yiimpadmin "yiimp coin UTC delete"
 sudo sg yiimpadmin "yiimp coin 888 delete"
 sudo sg yiimpadmin "yiimp coin EFL delete"
 sudo sg yiimpadmin "yiimp coin DIME delete"
 sudo sg yiimpadmin "yiimp coin SLR delete"
 sudo sg yiimpadmin "yiimp coin WATER delete"
 sudo sg yiimpadmin "yiimp coin NLG delete"
 sudo sg yiimpadmin "yiimp coin GIVE delete"
 sudo sg yiimpadmin "yiimp coin WC delete"
 sudo sg yiimpadmin "yiimp coin NOBL delete"
 sudo sg yiimpadmin "yiimp coin BITS delete"
 sudo sg yiimpadmin "yiimp coin BLU delete"
 sudo sg yiimpadmin "yiimp coin OC delete"
 sudo sg yiimpadmin "yiimp coin THC delete"
 sudo sg yiimpadmin "yiimp coin ENRG delete"
 sudo sg yiimpadmin "yiimp coin SHIBE delete"
 sudo sg yiimpadmin "yiimp coin SFR delete"
 sudo sg yiimpadmin "yiimp coin NAUT delete"
 sudo sg yiimpadmin "yiimp coin VRC delete"
 sudo sg yiimpadmin "yiimp coin CURE delete"
 sudo sg yiimpadmin "yiimp coin SYNC delete"
 sudo sg yiimpadmin "yiimp coin BLC delete"
 sudo sg yiimpadmin "yiimp coin XSI delete"
 sudo sg yiimpadmin "yiimp coin XC delete"
 sudo sg yiimpadmin "yiimp coin XDQ delete"
 sudo sg yiimpadmin "yiimp coin MMXIV delete"
 sudo sg yiimpadmin "yiimp coin CAIX delete"
 sudo sg yiimpadmin "yiimp coin BBR delete"
 sudo sg yiimpadmin "yiimp coin HYPER delete"
 sudo sg yiimpadmin "yiimp coin CCN delete"
 sudo sg yiimpadmin "yiimp coin KTK delete"
 sudo sg yiimpadmin "yiimp coin MUGA delete"
 sudo sg yiimpadmin "yiimp coin VOOT delete"
 sudo sg yiimpadmin "yiimp coin BN delete"
 sudo sg yiimpadmin "yiimp coin XMR delete"
 sudo sg yiimpadmin "yiimp coin CLOAK delete"
 sudo sg yiimpadmin "yiimp coin CHCC delete"
 sudo sg yiimpadmin "yiimp coin BURN delete"
 sudo sg yiimpadmin "yiimp coin KORE delete"
 sudo sg yiimpadmin "yiimp coin RZR delete"
 sudo sg yiimpadmin "yiimp coin XDN delete"
 sudo sg yiimpadmin "yiimp coin MIN delete"
 sudo sg yiimpadmin "yiimp coin TECH delete"
 sudo sg yiimpadmin "yiimp coin GML delete"
 sudo sg yiimpadmin "yiimp coin TRK delete"
 sudo sg yiimpadmin "yiimp coin WKC delete"
 sudo sg yiimpadmin "yiimp coin QTL delete"
 sudo sg yiimpadmin "yiimp coin XXX delete"
 sudo sg yiimpadmin "yiimp coin AERO delete"
 sudo sg yiimpadmin "yiimp coin TRUST delete"
 sudo sg yiimpadmin "yiimp coin BRIT delete"
 sudo sg yiimpadmin "yiimp coin JUDGE delete"
 sudo sg yiimpadmin "yiimp coin NAV delete"
 sudo sg yiimpadmin "yiimp coin XST delete"
 sudo sg yiimpadmin "yiimp coin APEX delete"
 sudo sg yiimpadmin "yiimp coin ZET delete"
 sudo sg yiimpadmin "yiimp coin BTCD delete"
 sudo sg yiimpadmin "yiimp coin KEY delete"
 sudo sg yiimpadmin "yiimp coin NUD delete"
 sudo sg yiimpadmin "yiimp coin TRI delete"
 sudo sg yiimpadmin "yiimp coin PES delete"
 sudo sg yiimpadmin "yiimp coin ICG delete"
 sudo sg yiimpadmin "yiimp coin UNO delete"
 sudo sg yiimpadmin "yiimp coin ESC delete"
 sudo sg yiimpadmin "yiimp coin PINK delete"
 sudo sg yiimpadmin "yiimp coin IOC delete"
 sudo sg yiimpadmin "yiimp coin SDC delete"
 sudo sg yiimpadmin "yiimp coin RAW delete"
 sudo sg yiimpadmin "yiimp coin MAX delete"
 sudo sg yiimpadmin "yiimp coin LXC delete"
 sudo sg yiimpadmin "yiimp coin BOOM delete"
 sudo sg yiimpadmin "yiimp coin BOB delete"
 sudo sg yiimpadmin "yiimp coin UNAT delete"
 sudo sg yiimpadmin "yiimp coin MWC delete"
 sudo sg yiimpadmin "yiimp coin VAULT delete"
 sudo sg yiimpadmin "yiimp coin FC2 delete"
 sudo sg yiimpadmin "yiimp coin SSD delete"
 sudo sg yiimpadmin "yiimp coin BIG delete"
 sudo sg yiimpadmin "yiimp coin GB delete"
 sudo sg yiimpadmin "yiimp coin ROOT delete"
 sudo sg yiimpadmin "yiimp coin AXR delete"
 sudo sg yiimpadmin "yiimp coin RIPO delete"
 sudo sg yiimpadmin "yiimp coin FIBRE delete"
 sudo sg yiimpadmin "yiimp coin SHADE delete"
 sudo sg yiimpadmin "yiimp coin FLEX delete"
 sudo sg yiimpadmin "yiimp coin XBOT delete"
 sudo sg yiimpadmin "yiimp coin XCASH delete"
 sudo sg yiimpadmin "yiimp coin NKT delete"
 sudo sg yiimpadmin "yiimp coin TTC delete"
 sudo sg yiimpadmin "yiimp coin CLAM delete"
 sudo sg yiimpadmin "yiimp coin VTR delete"
 sudo sg yiimpadmin "yiimp coin SUPER delete"
 sudo sg yiimpadmin "yiimp coin NOO delete"
 sudo sg yiimpadmin "yiimp coin XPY delete"
 sudo sg yiimpadmin "yiimp coin SMLY delete"
 sudo sg yiimpadmin "yiimp coin BCENT delete"
 sudo sg yiimpadmin "yiimp coin DS delete"
 sudo sg yiimpadmin "yiimp coin FAIR delete"
 sudo sg yiimpadmin "yiimp coin EVENT delete"
 sudo sg yiimpadmin "yiimp coin HUC delete"
 sudo sg yiimpadmin "yiimp coin CAT delete"
 sudo sg yiimpadmin "yiimp coin WDC delete"
 sudo sg yiimpadmin "yiimp coin BTM delete"
 sudo sg yiimpadmin "yiimp coin RMS delete"
 sudo sg yiimpadmin "yiimp coin ANC delete"
 sudo sg yiimpadmin "yiimp coin MEC delete"
 sudo sg yiimpadmin "yiimp coin MONA delete"
 sudo sg yiimpadmin "yiimp coin DGC delete"
 sudo sg yiimpadmin "yiimp coin BCF delete"
 sudo sg yiimpadmin "yiimp coin SYS delete"
 sudo sg yiimpadmin "yiimp coin ULTC delete"
 sudo sg yiimpadmin "yiimp coin CXC delete"
 sudo sg yiimpadmin "yiimp coin METAL delete"
 sudo sg yiimpadmin "yiimp coin SPR delete"
 sudo sg yiimpadmin "yiimp coin CBR delete"
 sudo sg yiimpadmin "yiimp coin FIND delete"
 sudo sg yiimpadmin "yiimp coin AM delete"
 sudo sg yiimpadmin "yiimp coin FUD delete"
 sudo sg yiimpadmin "yiimp coin ERM delete"
 sudo sg yiimpadmin "yiimp coin VIA delete"
 sudo sg yiimpadmin "yiimp coin CKC delete"
 sudo sg yiimpadmin "yiimp coin BTS delete"
 sudo sg yiimpadmin "yiimp coin DEAF delete"
 sudo sg yiimpadmin "yiimp coin HIC delete"
 sudo sg yiimpadmin "yiimp coin BAY delete"
 sudo sg yiimpadmin "yiimp coin VIOR delete"
 sudo sg yiimpadmin "yiimp coin VPN delete"
 sudo sg yiimpadmin "yiimp coin MN delete"
 sudo sg yiimpadmin "yiimp coin EXE delete"
 sudo sg yiimpadmin "yiimp coin PFC delete"
 sudo sg yiimpadmin "yiimp coin GSX delete"
 sudo sg yiimpadmin "yiimp coin BRXv2 delete"
 sudo sg yiimpadmin "yiimp coin ACHK delete"
 sudo sg yiimpadmin "yiimp coin CRYPT delete"
 sudo sg yiimpadmin "yiimp coin HLC delete"
 sudo sg yiimpadmin "yiimp coin SWIFT delete"
 sudo sg yiimpadmin "yiimp coin ARCH delete"
 sudo sg yiimpadmin "yiimp coin GAIA delete"
 sudo sg yiimpadmin "yiimp coin WWC delete"
 sudo sg yiimpadmin "yiimp coin XRP delete"
 sudo sg yiimpadmin "yiimp coin LMR delete"
 sudo sg yiimpadmin "yiimp coin MNE delete"
 sudo sg yiimpadmin "yiimp coin CRW delete"
 sudo sg yiimpadmin "yiimp coin VDO delete"
 sudo sg yiimpadmin "yiimp coin NOPE delete"
 sudo sg yiimpadmin "yiimp coin XWT delete"
 sudo sg yiimpadmin "yiimp coin DTC delete"
 sudo sg yiimpadmin "yiimp coin SMBR delete"
 sudo sg yiimpadmin "yiimp coin HYP delete"
 sudo sg yiimpadmin "yiimp coin QBK delete"
 sudo sg yiimpadmin "yiimp coin CENT delete"
 sudo sg yiimpadmin "yiimp coin BLOCK delete"
 sudo sg yiimpadmin "yiimp coin CATC delete"
 sudo sg yiimpadmin "yiimp coin SCSY delete"
 sudo sg yiimpadmin "yiimp coin ABY delete"
 sudo sg yiimpadmin "yiimp coin BALLS delete"
 sudo sg yiimpadmin "yiimp coin QSLV delete"
 sudo sg yiimpadmin "yiimp coin U delete"
 sudo sg yiimpadmin "yiimp coin BYC delete"
 sudo sg yiimpadmin "yiimp coin BUN delete"
 sudo sg yiimpadmin "yiimp coin ZER delete"
 sudo sg yiimpadmin "yiimp coin ZNY delete"
 sudo sg yiimpadmin "yiimp coin MRY delete"
 sudo sg yiimpadmin "yiimp coin CANN delete"
 sudo sg yiimpadmin "yiimp coin POT delete"
 sudo sg yiimpadmin "yiimp coin TAG delete"
 sudo sg yiimpadmin "yiimp coin RBY delete"
 sudo sg yiimpadmin "yiimp coin NOTE delete"
 sudo sg yiimpadmin "yiimp coin LTC delete"
 sudo sg yiimpadmin "yiimp coin NVC delete"
 sudo sg yiimpadmin "yiimp coin 42 delete"
 sudo sg yiimpadmin "yiimp coin JBS delete"
 sudo sg yiimpadmin "yiimp coin LSD delete"
 sudo sg yiimpadmin "yiimp coin J delete"
 sudo sg yiimpadmin "yiimp coin SLG delete"
 sudo sg yiimpadmin "yiimp coin VIK delete"
 sudo sg yiimpadmin "yiimp coin RPC delete"
 sudo sg yiimpadmin "yiimp coin XG delete"
 sudo sg yiimpadmin "yiimp coin DP delete"
 sudo sg yiimpadmin "yiimp coin MARYJ delete"
 sudo sg yiimpadmin "yiimp coin XMG delete"
 sudo sg yiimpadmin "yiimp coin RUBLE delete"
 sudo sg yiimpadmin "yiimp coin XCLD delete"
 sudo sg yiimpadmin "yiimp coin BST delete"
 sudo sg yiimpadmin "yiimp coin HNC delete"
 sudo sg yiimpadmin "yiimp coin GXG delete"
 sudo sg yiimpadmin "yiimp coin BTX delete"
 sudo sg yiimpadmin "yiimp coin 007 delete"
 sudo sg yiimpadmin "yiimp coin LUX delete"
 sudo sg yiimpadmin "yiimp coin ACP delete"
 sudo sg yiimpadmin "yiimp coin STR delete"
 sudo sg yiimpadmin "yiimp coin PAC delete"
 sudo sg yiimpadmin "yiimp coin PPC delete"
 sudo sg yiimpadmin "yiimp coin MLS delete"
 sudo sg yiimpadmin "yiimp coin FLO delete"
 sudo sg yiimpadmin "yiimp coin PTC delete"
 sudo sg yiimpadmin "yiimp coin GUN delete"
 sudo sg yiimpadmin "yiimp coin DOGE delete"
echo -e "$GREEN Junk coin removal completed...$COL_RESET"


sudo rm -r $STORAGE_ROOT/yiimp/yiimp_setup
cd $HOME/multipool/yiimp_single
