#####################################################
# Created by cryptopool.builders for crypto use...
#####################################################

source /etc/functions.sh
source $STORAGE_ROOT/yiimp/.yiimp.conf
cd $HOME/multipool/yiimp_single

echo -e " Installing cron screens to crontab...$COL_RESET"
(crontab -l 2>/dev/null; echo "@reboot sleep 20 && /home/crypto-data/yiimp/starts/screens.start.sh") | crontab -
if [[ ("$CoinPort" == "no") ]]; then
(crontab -l 2>/dev/null; echo "@reboot sleep 20 && /home/crypto-data/yiimp/starts/stratum.start.sh") | crontab -
fi
(crontab -l 2>/dev/null; echo "@reboot source /etc/functions.sh") | crontab -
(crontab -l 2>/dev/null; echo "@reboot source /etc/multipool.conf") | crontab -
sudo cp -r first_boot.sh $STORAGE_ROOT/yiimp/
echo -e "$GREEN Crontab system complete...$COL_RESET"

echo -e " Creating YiiMP Screens startup script...$COL_RESET"

echo '#!/usr/bin/env bash
source /etc/multipool.conf
# Ugly way to remove junk coins from initial YiiMP database on first boot
source $STORAGE_ROOT/yiimp/.yiimp.conf
if [[ ! -e '$STORAGE_ROOT/yiimp/first_boot.sh' ]]; then
echo
else
source $STORAGE_ROOT/yiimp/first_boot.sh
fi
################################################################################
# Author: cryptopool.builders
#
#
# Program: yiimp screen startup script
#
# BTC Donation: 12Pt3vQhQpXvyzBd5qcoL17ouhNFyihyz5
#
################################################################################
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/.
sudo chmod 777 $STORAGE_ROOT/yiimp/site/log/debug.log
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
CRONS=$STORAGE_ROOT/yiimp/site/crons
screen -dmS main bash $CRONS/main.sh
screen -dmS loop2 bash $CRONS/loop2.sh
screen -dmS blocks bash $CRONS/blocks.sh
screen -dmS debug tail -f $LOG_DIR/debug.log
' | sudo -E tee $STORAGE_ROOT/yiimp/starts/screens.start.sh >/dev/null 2>&1
sudo chmod +x $STORAGE_ROOT/yiimp/starts/screens.start.sh

echo -e " Creating Stratum screens start script...$COL_RESET"

echo '#!/usr/bin/env bash
################################################################################
# Author: cryptopool.builders
#
#
# Program: yiimp stratum startup script
#
# BTC Donation: 12Pt3vQhQpXvyzBd5qcoL17ouhNFyihyz5
#
################################################################################
source /etc/multipool.conf
source $STORAGE_ROOT/yiimp/.yiimp.conf
STRATUM_DIR=$STORAGE_ROOT/yiimp/site/stratum
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
screen -dmS c11 bash $STRATUM_DIR/run.sh c11
screen -dmS deep bash $STRATUM_DIR/run.sh deep
screen -dmS x11 bash $STRATUM_DIR/run.sh x11
screen -dmS 2x11evo bash $STRATUM_DIR/run.sh x11evo
screen -dmS x13 bash $STRATUM_DIR/run.sh x13
screen -dmS x14 bash bash $STRATUM_DIR/run.sh x14
screen -dmS x15 bash $STRATUM_DIR/run.sh x15
screen -dmS x17 bash $STRATUM_DIR/run.sh x17
screen -dmS xevan bash $STRATUM_DIR/run.sh xevan
screen -dmS timetravel bash $STRATUM_DIR/run.sh timetravel
screen -dmS bitcore bash $STRATUM_DIR/run.sh bitcore
screen -dmS hmq1725 bash $STRATUM_DIR/run.sh hmq1725
screen -dmS tribus bash $STRATUM_DIR/run.sh tribus
screen -dmS sha bash $STRATUM_DIR/run.sh sha
screen -dmS 2sha256t bash $STRATUM_DIR/run.sh sha256t
screen -dmS scrypt bash $STRATUM_DIR/run.sh scrypt
screen -dmS 2scryptn bash $STRATUM_DIR/run.sh scryptn
screen -dmS luffa bash $STRATUM_DIR/run.sh luffa
screen -dmS neo bash $STRATUM_DIR/run.sh neo
screen -dmS nist5 bash $STRATUM_DIR/run.sh nist5
screen -dmS penta bash $STRATUM_DIR/run.sh penta
screen -dmS quark bash $STRATUM_DIR/run.sh quark
screen -dmS qubit bash $STRATUM_DIR/run.sh qubit
screen -dmS jha bash $STRATUM_DIR/run.sh jha
screen -dmS dmd-gr bash $STRATUM_DIR/run.sh dmd-gr
screen -dmS myr-gr bash $STRATUM_DIR/run.sh myr-gr
screen -dmS lbry bash $STRATUM_DIR/run.sh lbry
screen -dmS lyra2 bash $STRATUM_DIR/run.sh lyra2
screen -dmS 2lyra2v2 bash $STRATUM_DIR/run.sh lyra2v2
screen -dmS zero bash $STRATUM_DIR/run.sh lyra2z
screen -dmS blakecoin bash $STRATUM_DIR/run.sh blakecoin # blake 8
screen -dmS blake bash $STRATUM_DIR/run.sh blake
screen -dmS 2blake2s bash $STRATUM_DIR/run.sh blake2s
screen -dmS vanilla bash $STRATUM_DIR/run.sh vanilla # blake 8
screen -dmS decred bash $STRATUM_DIR/run.sh decred # blake 14
screen -dmS keccak bash $STRATUM_DIR/run.sh keccak
screen -dmS whirlpool bash $STRATUM_DIR/run.sh whirlpool
screen -dmS skein bash $STRATUM_DIR/run.sh skein
screen -dmS 2skein2 bash $STRATUM_DIR/run.sh skein2
screen -dmS yescrypt bash $STRATUM_DIR/run.sh yescrypt
screen -dmS zr5 bash $STRATUM_DIR/run.sh zr5
screen -dmS sib bash $STRATUM_DIR/run.sh sib
screen -dmS m7m sudo bash $STRATUM_DIR/run.sh m7m
screen -dmS veltor bash $STRATUM_DIR/run.sh veltor
screen -dmS velvet bash $STRATUM_DIR/run.sh velvet
screen -dmS argon2 bash $STRATUM_DIR/run.sh argon2
screen -dmS groestl bash $STRATUM_DIR/run.sh groestl
screen -dmS skunk bash $STRATUM_DIR/run.sh skunk
screen -dmS phi1612 bash $STRATUM_DIR/run.sh phi1612
screen -dmS hsr bash $STRATUM_DIR/run.sh hsr
screen -dmS yescryptr16 bash $STRATUM_DIR/run.sh yescryptR16
screen -dmS x16r bash $STRATUM_DIR/run.sh x16r
' | sudo -E tee $STORAGE_ROOT/yiimp/starts/stratum.start.sh >/dev/null 2>&1
sudo chmod +x $STORAGE_ROOT/yiimp/starts/stratum.start.sh

echo '
source /etc/multipool.conf
source $STORAGE_ROOT/yiimp/.yiimp.conf
LOG_DIR=$STORAGE_ROOT/yiimp/site/log
CRONS=$STORAGE_ROOT/yiimp/site/crons
STRATUM_DIR=$STORAGE_ROOT/yiimp/site/stratum
' | sudo -E tee $STORAGE_ROOT/yiimp/.prescreens.start.conf >/dev/null 2>&1

echo "source /etc/multipool.conf" | hide_output tee -a ~/.bashrc
echo "source $STORAGE_ROOT/yiimp/.prescreens.start.conf" | hide_output tee -a ~/.bashrc
echo -e "$GREEN YiiMP Screens added...$COL_RESET"

exec sudo su -l $USER
echo "Removing junk coins from YiiMP Database, this may take several minutes...$COL_RESET"
hide_output & spinner sg yiimpadmin "yiimp coin MDT delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLAX delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRP delete"
hide_output & spinner sg yiimpadmin "yiimp coin VTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin UFO delete"
hide_output & spinner sg yiimpadmin "yiimp coin PXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin HAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin XAI delete"
hide_output & spinner sg yiimpadmin "yiimp coin QRK delete"
hide_output & spinner sg yiimpadmin "yiimp coin MUE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BOD delete"
hide_output & spinner sg yiimpadmin "yiimp coin SRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTQ delete"
hide_output & spinner sg yiimpadmin "yiimp coin GEO delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGB delete"
hide_output & spinner sg yiimpadmin "yiimp coin CYP delete"
hide_output & spinner sg yiimpadmin "yiimp coin IDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NEOS delete"
hide_output & spinner sg yiimpadmin "yiimp coin MYR delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin LOG delete"
hide_output & spinner sg yiimpadmin "yiimp coin ILM delete"
hide_output & spinner sg yiimpadmin "yiimp coin START delete"
hide_output & spinner sg yiimpadmin "yiimp coin URO delete"
hide_output & spinner sg yiimpadmin "yiimp coin DASH delete"
hide_output & spinner sg yiimpadmin "yiimp coin BSC delete"
hide_output & spinner sg yiimpadmin "yiimp coin HEDG delete"
hide_output & spinner sg yiimpadmin "yiimp coin AMBER delete"
hide_output & spinner sg yiimpadmin "yiimp coin HTML5 delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNF delete"
hide_output & spinner sg yiimpadmin "yiimp coin DES delete"
hide_output & spinner sg yiimpadmin "yiimp coin KUMA delete"
hide_output & spinner sg yiimpadmin "yiimp coin MEME delete"
hide_output & spinner sg yiimpadmin "yiimp coin FOOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin UMO delete"
hide_output & spinner sg yiimpadmin "yiimp coin G3N delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHND delete"
hide_output & spinner sg yiimpadmin "yiimp coin WHIPPED delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLY delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUMBA delete"
hide_output & spinner sg yiimpadmin "yiimp coin EBG delete"
hide_output & spinner sg yiimpadmin "yiimp coin I0C delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAPT delete"
hide_output & spinner sg yiimpadmin "yiimp coin PAK delete"
hide_output & spinner sg yiimpadmin "yiimp coin EUC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRE-OLD delete"
hide_output & spinner sg yiimpadmin "yiimp coin PR delete"
hide_output & spinner sg yiimpadmin "yiimp coin VGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CFC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GAME delete"
hide_output & spinner sg yiimpadmin "yiimp coin FONZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin DBIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRUMP delete"
hide_output & spinner sg yiimpadmin "yiimp coin JIF delete"
hide_output & spinner sg yiimpadmin "yiimp coin EVIL delete"
hide_output & spinner sg yiimpadmin "yiimp coin EVO delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin SANDG delete"
hide_output & spinner sg yiimpadmin "yiimp coin RICHX delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGCS delete"
hide_output & spinner sg yiimpadmin "yiimp coin BOLI delete"
hide_output & spinner sg yiimpadmin "yiimp coin LGBTQ delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZOOM delete"
hide_output & spinner sg yiimpadmin "yiimp coin YOC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SIB delete"
hide_output & spinner sg yiimpadmin "yiimp coin OPES delete"
hide_output & spinner sg yiimpadmin "yiimp coin NKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MMXVI delete"
hide_output & spinner sg yiimpadmin "yiimp coin MBL delete"
hide_output & spinner sg yiimpadmin "yiimp coin KNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin AR2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin AND delete"
hide_output & spinner sg yiimpadmin "yiimp coin TROLL delete"
hide_output & spinner sg yiimpadmin "yiimp coin DNET delete"
hide_output & spinner sg yiimpadmin "yiimp coin DCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin EGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MND delete"
hide_output & spinner sg yiimpadmin "yiimp coin BNT delete"
hide_output & spinner sg yiimpadmin "yiimp coin AMS delete"
hide_output & spinner sg yiimpadmin "yiimp coin INFX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin HTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CZECO delete"
hide_output & spinner sg yiimpadmin "yiimp coin EDRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FTP delete"
hide_output & spinner sg yiimpadmin "yiimp coin OP delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHAI delete"
hide_output & spinner sg yiimpadmin "yiimp coin REV delete"
hide_output & spinner sg yiimpadmin "yiimp coin PULSE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCT delete"
hide_output & spinner sg yiimpadmin "yiimp coin STS delete"
hide_output & spinner sg yiimpadmin "yiimp coin EC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CYG delete"
hide_output & spinner sg yiimpadmin "yiimp coin VAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin TBC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRBIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin GMX delete"
hide_output & spinner sg yiimpadmin "yiimp coin HODL delete"
hide_output & spinner sg yiimpadmin "yiimp coin KLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUZZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin RBIES delete"
hide_output & spinner sg yiimpadmin "yiimp coin SEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XID delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCU delete"
hide_output & spinner sg yiimpadmin "yiimp coin WARP delete"
hide_output & spinner sg yiimpadmin "yiimp coin CPNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin HIRE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLS delete"
hide_output & spinner sg yiimpadmin "yiimp coin XHI delete"
hide_output & spinner sg yiimpadmin "yiimp coin RADS delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTP delete"
hide_output & spinner sg yiimpadmin "yiimp coin X2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin HMP delete"
hide_output & spinner sg yiimpadmin "yiimp coin BRONZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin RUBIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin REP delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPL delete"
hide_output & spinner sg yiimpadmin "yiimp coin CIONZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin SCRT delete"
hide_output & spinner sg yiimpadmin "yiimp coin DEUR delete"
hide_output & spinner sg yiimpadmin "yiimp coin VOX delete"
hide_output & spinner sg yiimpadmin "yiimp coin CLUB delete"
hide_output & spinner sg yiimpadmin "yiimp coin SCOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLOZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin STATS delete"
hide_output & spinner sg yiimpadmin "yiimp coin HZDOGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin WLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BITUSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin BITCNY delete"
hide_output & spinner sg yiimpadmin "yiimp coin FNX delete"
hide_output & spinner sg yiimpadmin "yiimp coin APC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XLM delete"
hide_output & spinner sg yiimpadmin "yiimp coin AGRS delete"
hide_output & spinner sg yiimpadmin "yiimp coin DROP delete"
hide_output & spinner sg yiimpadmin "yiimp coin AMP delete"
hide_output & spinner sg yiimpadmin "yiimp coin ANTI delete"
hide_output & spinner sg yiimpadmin "yiimp coin 1337 delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRBO delete"
hide_output & spinner sg yiimpadmin "yiimp coin BIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SOIL delete"
hide_output & spinner sg yiimpadmin "yiimp coin OMNI delete"
hide_output & spinner sg yiimpadmin "yiimp coin CUBE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin WOP delete"
hide_output & spinner sg yiimpadmin "yiimp coin FCT delete"
hide_output & spinner sg yiimpadmin "yiimp coin PRT delete"
hide_output & spinner sg yiimpadmin "yiimp coin CBIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin NEU delete"
hide_output & spinner sg yiimpadmin "yiimp coin STEPS delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXP delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCY delete"
hide_output & spinner sg yiimpadmin "yiimp coin PRIME delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHF delete"
hide_output & spinner sg yiimpadmin "yiimp coin SWING delete"
hide_output & spinner sg yiimpadmin "yiimp coin MI delete"
hide_output & spinner sg yiimpadmin "yiimp coin MACRO delete"
hide_output & spinner sg yiimpadmin "yiimp coin SC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin MAPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TX delete"
hide_output & spinner sg yiimpadmin "yiimp coin ETH delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRE delete"
hide_output & spinner sg yiimpadmin "yiimp coin AEON delete"
hide_output & spinner sg yiimpadmin "yiimp coin GSY delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHIP delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCHC delete"
hide_output & spinner sg yiimpadmin "yiimp coin AXIOM delete"
hide_output & spinner sg yiimpadmin "yiimp coin FUEL delete"
hide_output & spinner sg yiimpadmin "yiimp coin BIOS delete"
hide_output & spinner sg yiimpadmin "yiimp coin CPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin IBITS delete"
hide_output & spinner sg yiimpadmin "yiimp coin DIGS delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MCZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin BANX delete"
hide_output & spinner sg yiimpadmin "yiimp coin CPN delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPRTS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPROUT delete"
hide_output & spinner sg yiimpadmin "yiimp coin NUKE delete"
hide_output & spinner sg yiimpadmin "yiimp coin 2BACCO delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin LFO delete"
hide_output & spinner sg yiimpadmin "yiimp coin VERSA delete"
hide_output & spinner sg yiimpadmin "yiimp coin MCAR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CARB delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZUR delete"
hide_output & spinner sg yiimpadmin "yiimp coin VAPE delete"
hide_output & spinner sg yiimpadmin "yiimp coin TALK delete"
hide_output & spinner sg yiimpadmin "yiimp coin RUM delete"
hide_output & spinner sg yiimpadmin "yiimp coin PPCD delete"
hide_output & spinner sg yiimpadmin "yiimp coin PHO delete"
hide_output & spinner sg yiimpadmin "yiimp coin P0001 delete"
hide_output & spinner sg yiimpadmin "yiimp coin NODE delete"
hide_output & spinner sg yiimpadmin "yiimp coin MRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ISO delete"
hide_output & spinner sg yiimpadmin "yiimp coin HANSA delete"
hide_output & spinner sg yiimpadmin "yiimp coin FX01 delete"
hide_output & spinner sg yiimpadmin "yiimp coin FRSH delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIMK delete"
hide_output & spinner sg yiimpadmin "yiimp coin FAIL delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRM delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CV2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTRHA delete"
hide_output & spinner sg yiimpadmin "yiimp coin ALCUREX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BNX delete"
hide_output & spinner sg yiimpadmin "yiimp coin QUIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin V delete"
hide_output & spinner sg yiimpadmin "yiimp coin PLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRW delete"
hide_output & spinner sg yiimpadmin "yiimp coin DUO delete"
hide_output & spinner sg yiimpadmin "yiimp coin ANI delete"
hide_output & spinner sg yiimpadmin "yiimp coin CDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CX delete"
hide_output & spinner sg yiimpadmin "yiimp coin MARS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHA delete"
hide_output & spinner sg yiimpadmin "yiimp coin FETISH delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BDSM delete"
hide_output & spinner sg yiimpadmin "yiimp coin OFF delete"
hide_output & spinner sg yiimpadmin "yiimp coin EMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHAO delete"
hide_output & spinner sg yiimpadmin "yiimp coin CNO delete"
hide_output & spinner sg yiimpadmin "yiimp coin FUNK delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DUCK delete"
hide_output & spinner sg yiimpadmin "yiimp coin BSY delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPN delete"
hide_output & spinner sg yiimpadmin "yiimp coin IPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin '"'$MINEZ'"' delete"
hide_output & spinner sg yiimpadmin "yiimp coin '"'$MINEW'"' delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADD delete"
hide_output & spinner sg yiimpadmin "yiimp coin '"'$MINE'"' delete"
hide_output & spinner sg yiimpadmin "yiimp coin FTCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CIV delete"
hide_output & spinner sg yiimpadmin "yiimp coin TOP delete"
hide_output & spinner sg yiimpadmin "yiimp coin TTY delete"
hide_output & spinner sg yiimpadmin "yiimp coin NTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin KIWI delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPL delete"
hide_output & spinner sg yiimpadmin "yiimp coin XGR delete"
hide_output & spinner sg yiimpadmin "yiimp coin '"'$$$'"' delete"
hide_output & spinner sg yiimpadmin "yiimp coin 66 delete"
hide_output & spinner sg yiimpadmin "yiimp coin MDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DARK delete"
hide_output & spinner sg yiimpadmin "yiimp coin POP delete"
hide_output & spinner sg yiimpadmin "yiimp coin WSX delete"
hide_output & spinner sg yiimpadmin "yiimp coin DOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin YOVI delete"
hide_output & spinner sg yiimpadmin "yiimp coin HXX delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRPS delete"
hide_output & spinner sg yiimpadmin "yiimp coin BAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin SJW delete"
hide_output & spinner sg yiimpadmin "yiimp coin GMCX delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPX delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXT delete"
hide_output & spinner sg yiimpadmin "yiimp coin TENNET delete"
hide_output & spinner sg yiimpadmin "yiimp coin KC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLUS delete"
hide_output & spinner sg yiimpadmin "yiimp coin XRA delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin EA delete"
hide_output & spinner sg yiimpadmin "yiimp coin TAGR delete"
hide_output & spinner sg yiimpadmin "yiimp coin HAZE delete"
hide_output & spinner sg yiimpadmin "yiimp coin TAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin POLY delete"
hide_output & spinner sg yiimpadmin "yiimp coin INDEX delete"
hide_output & spinner sg yiimpadmin "yiimp coin GENI delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUCKS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPKTR delete"
hide_output & spinner sg yiimpadmin "yiimp coin GENE delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRM delete"
hide_output & spinner sg yiimpadmin "yiimp coin DIBS delete"
hide_output & spinner sg yiimpadmin "yiimp coin GTFO delete"
hide_output & spinner sg yiimpadmin "yiimp coin FUTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XVI delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLOBE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SMSR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CIRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin WOC2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin NODX delete"
hide_output & spinner sg yiimpadmin "yiimp coin ERC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SEN delete"
hide_output & spinner sg yiimpadmin "yiimp coin SAK delete"
hide_output & spinner sg yiimpadmin "yiimp coin EOC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRANSF delete"
hide_output & spinner sg yiimpadmin "yiimp coin GEN delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRKT delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPH delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIST delete"
hide_output & spinner sg yiimpadmin "yiimp coin DUB delete"
hide_output & spinner sg yiimpadmin "yiimp coin VAPOR delete"
hide_output & spinner sg yiimpadmin "yiimp coin ARPA delete"
hide_output & spinner sg yiimpadmin "yiimp coin BNB delete"
hide_output & spinner sg yiimpadmin "yiimp coin NANAS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SEEDS delete"
hide_output & spinner sg yiimpadmin "yiimp coin OPTION delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRA delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLUCK delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXB delete"
hide_output & spinner sg yiimpadmin "yiimp coin GREED delete"
hide_output & spinner sg yiimpadmin "yiimp coin MOIN delete"
hide_output & spinner sg yiimpadmin "yiimp coin Vcoin  delete"
hide_output & spinner sg yiimpadmin "yiimp coin TWLV delete"
hide_output & spinner sg yiimpadmin "yiimp coin RDN delete"
hide_output & spinner sg yiimpadmin "yiimp coin PSY delete"
hide_output & spinner sg yiimpadmin "yiimp coin ECC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SNRG delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CREVA delete"
hide_output & spinner sg yiimpadmin "yiimp coin VCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin 32BIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin XNA delete"
hide_output & spinner sg yiimpadmin "yiimp coin TWERK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CS delete"
hide_output & spinner sg yiimpadmin "yiimp coin GENIUS delete"
hide_output & spinner sg yiimpadmin "yiimp coin PRE delete"
hide_output & spinner sg yiimpadmin "yiimp coin NICE delete"
hide_output & spinner sg yiimpadmin "yiimp coin CORG delete"
hide_output & spinner sg yiimpadmin "yiimp coin DB delete"
hide_output & spinner sg yiimpadmin "yiimp coin EQM delete"
hide_output & spinner sg yiimpadmin "yiimp coin FADE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SED delete"
hide_output & spinner sg yiimpadmin "yiimp coin SKB delete"
hide_output & spinner sg yiimpadmin "yiimp coin TNG delete"
hide_output & spinner sg yiimpadmin "yiimp coin ARB delete"
hide_output & spinner sg yiimpadmin "yiimp coin DCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PTA delete"
hide_output & spinner sg yiimpadmin "yiimp coin MRB delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTA delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRT delete"
hide_output & spinner sg yiimpadmin "yiimp coin AST delete"
hide_output & spinner sg yiimpadmin "yiimp coin BA delete"
hide_output & spinner sg yiimpadmin "yiimp coin KRAK delete"
hide_output & spinner sg yiimpadmin "yiimp coin M1 delete"
hide_output & spinner sg yiimpadmin "yiimp coin 16BIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin TB delete"
hide_output & spinner sg yiimpadmin "yiimp coin BIT16 delete"
hide_output & spinner sg yiimpadmin "yiimp coin CLV delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHELL delete"
hide_output & spinner sg yiimpadmin "yiimp coin LIMX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTI delete"
hide_output & spinner sg yiimpadmin "yiimp coin FSN delete"
hide_output & spinner sg yiimpadmin "yiimp coin TKT delete"
hide_output & spinner sg yiimpadmin "yiimp coin FCS delete"
hide_output & spinner sg yiimpadmin "yiimp coin VTN delete"
hide_output & spinner sg yiimpadmin "yiimp coin EPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PKB delete"
hide_output & spinner sg yiimpadmin "yiimp coin GAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin ISL delete"
hide_output & spinner sg yiimpadmin "yiimp coin VIRAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin UTLE delete"
hide_output & spinner sg yiimpadmin "yiimp coin PNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GOAT delete"
hide_output & spinner sg yiimpadmin "yiimp coin EPY delete"
hide_output & spinner sg yiimpadmin "yiimp coin CTO delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRAV delete"
hide_output & spinner sg yiimpadmin "yiimp coin GPH delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUB delete"
hide_output & spinner sg yiimpadmin "yiimp coin TDFB delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPHR delete"
hide_output & spinner sg yiimpadmin "yiimp coin GUM delete"
hide_output & spinner sg yiimpadmin "yiimp coin XMS delete"
hide_output & spinner sg yiimpadmin "yiimp coin XSEED delete"
hide_output & spinner sg yiimpadmin "yiimp coin XNX delete"
hide_output & spinner sg yiimpadmin "yiimp coin XTP delete"
hide_output & spinner sg yiimpadmin "yiimp coin DOX delete"
hide_output & spinner sg yiimpadmin "yiimp coin QTZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNAT-skein delete"
hide_output & spinner sg yiimpadmin "yiimp coin AIB delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin SIGU delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLITZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin NIRO delete"
hide_output & spinner sg yiimpadmin "yiimp coin HUGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin 7 delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin UIS-qubit delete"
hide_output & spinner sg yiimpadmin "yiimp coin UIS-skein delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLING delete"
hide_output & spinner sg yiimpadmin "yiimp coin COV delete"
hide_output & spinner sg yiimpadmin "yiimp coin NTRN delete"
hide_output & spinner sg yiimpadmin "yiimp coin CTK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CF delete"
hide_output & spinner sg yiimpadmin "yiimp coin CGN delete"
hide_output & spinner sg yiimpadmin "yiimp coin OK delete"
hide_output & spinner sg yiimpadmin "yiimp coin 8BIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin IEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin P7C delete"
hide_output & spinner sg yiimpadmin "yiimp coin HZT delete"
hide_output & spinner sg yiimpadmin "yiimp coin LEA delete"
hide_output & spinner sg yiimpadmin "yiimp coin GIZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin ETRUST delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPRO delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRON delete"
hide_output & spinner sg yiimpadmin "yiimp coin DECR delete"
hide_output & spinner sg yiimpadmin "yiimp coin RICE delete"
hide_output & spinner sg yiimpadmin "yiimp coin STP delete"
hide_output & spinner sg yiimpadmin "yiimp coin NXE delete"
hide_output & spinner sg yiimpadmin "yiimp coin AECC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PLANET delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIRE delete"
hide_output & spinner sg yiimpadmin "yiimp coin ANAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin MTLMC3 delete"
hide_output & spinner sg yiimpadmin "yiimp coin TWIST delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRIME delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin TEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin KARMA delete"
hide_output & spinner sg yiimpadmin "yiimp coin TCX delete"
hide_output & spinner sg yiimpadmin "yiimp coin TAB delete"
hide_output & spinner sg yiimpadmin "yiimp coin NDOGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin GIFT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BBCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRICK delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGMS delete"
hide_output & spinner sg yiimpadmin "yiimp coin CCB delete"
hide_output & spinner sg yiimpadmin "yiimp coin OZC delete"
hide_output & spinner sg yiimpadmin "yiimp coin STK delete"
hide_output & spinner sg yiimpadmin "yiimp coin SIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin EGG delete"
hide_output & spinner sg yiimpadmin "yiimp coin EKN delete"
hide_output & spinner sg yiimpadmin "yiimp coin MRP delete"
hide_output & spinner sg yiimpadmin "yiimp coin QORA delete"
hide_output & spinner sg yiimpadmin "yiimp coin PXL delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRY delete"
hide_output & spinner sg yiimpadmin "yiimp coin URC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ICN delete"
hide_output & spinner sg yiimpadmin "yiimp coin OCTO delete"
hide_output & spinner sg yiimpadmin "yiimp coin EUR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAD delete"
hide_output & spinner sg yiimpadmin "yiimp coin CC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XEM delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLFI delete"
hide_output & spinner sg yiimpadmin "yiimp coin 256 delete"
hide_output & spinner sg yiimpadmin "yiimp coin ICASH delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCRY delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDB delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZIRK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRAVE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BITZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin OMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PAY delete"
hide_output & spinner sg yiimpadmin "yiimp coin LDOGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin RBT delete"
hide_output & spinner sg yiimpadmin "yiimp coin ASN delete"
hide_output & spinner sg yiimpadmin "yiimp coin MINE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XAU delete"
hide_output & spinner sg yiimpadmin "yiimp coin XFC delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCO delete"
hide_output & spinner sg yiimpadmin "yiimp coin VOYA delete"
hide_output & spinner sg yiimpadmin "yiimp coin XVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin WBB delete"
hide_output & spinner sg yiimpadmin "yiimp coin ECASH delete"
hide_output & spinner sg yiimpadmin "yiimp coin MTR delete"
hide_output & spinner sg yiimpadmin "yiimp coin NSR delete"
hide_output & spinner sg yiimpadmin "yiimp coin GSM delete"
hide_output & spinner sg yiimpadmin "yiimp coin PTY delete"
hide_output & spinner sg yiimpadmin "yiimp coin LYB delete"
hide_output & spinner sg yiimpadmin "yiimp coin SUP delete"
hide_output & spinner sg yiimpadmin "yiimp coin CIN delete"
hide_output & spinner sg yiimpadmin "yiimp coin DD delete"
hide_output & spinner sg yiimpadmin "yiimp coin SMAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRID delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLM delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTS delete"
hide_output & spinner sg yiimpadmin "yiimp coin XTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGORE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BITB delete"
hide_output & spinner sg yiimpadmin "yiimp coin BEAN delete"
hide_output & spinner sg yiimpadmin "yiimp coin PEN delete"
hide_output & spinner sg yiimpadmin "yiimp coin NVCD delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPD delete"
hide_output & spinner sg yiimpadmin "yiimp coin CBX delete"
hide_output & spinner sg yiimpadmin "yiimp coin CELL delete"
hide_output & spinner sg yiimpadmin "yiimp coin KOBO delete"
hide_output & spinner sg yiimpadmin "yiimp coin LQD delete"
hide_output & spinner sg yiimpadmin "yiimp coin XTR delete"
hide_output & spinner sg yiimpadmin "yiimp coin 10K delete"
hide_output & spinner sg yiimpadmin "yiimp coin MYST delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCS delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPB delete"
hide_output & spinner sg yiimpadmin "yiimp coin CETI delete"
hide_output & spinner sg yiimpadmin "yiimp coin OMA delete"
hide_output & spinner sg yiimpadmin "yiimp coin CCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XFB delete"
hide_output & spinner sg yiimpadmin "yiimp coin OBS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SOON delete"
hide_output & spinner sg yiimpadmin "yiimp coin GIG delete"
hide_output & spinner sg yiimpadmin "yiimp coin XAP delete"
hide_output & spinner sg yiimpadmin "yiimp coin XBC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCH delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCP delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDP delete"
hide_output & spinner sg yiimpadmin "yiimp coin XUSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin YACC delete"
hide_output & spinner sg yiimpadmin "yiimp coin 1CR delete"
hide_output & spinner sg yiimpadmin "yiimp coin ACH delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADN delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin BELA delete"
hide_output & spinner sg yiimpadmin "yiimp coin C2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin CGA delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHA delete"
hide_output & spinner sg yiimpadmin "yiimp coin CNMT delete"
hide_output & spinner sg yiimpadmin "yiimp coin CYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DIEM delete"
hide_output & spinner sg yiimpadmin "yiimp coin DSH delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GAP delete"
hide_output & spinner sg yiimpadmin "yiimp coin GDN delete"
hide_output & spinner sg yiimpadmin "yiimp coin GEMZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin GOLD delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRS delete"
hide_output & spinner sg yiimpadmin "yiimp coin HIRO delete"
hide_output & spinner sg yiimpadmin "yiimp coin HZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin JLH delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTBC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MAID delete"
hide_output & spinner sg yiimpadmin "yiimp coin MCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin MIL delete"
hide_output & spinner sg yiimpadmin "yiimp coin MMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MMNXT delete"
hide_output & spinner sg yiimpadmin "yiimp coin MNTA delete"
hide_output & spinner sg yiimpadmin "yiimp coin MRS delete"
hide_output & spinner sg yiimpadmin "yiimp coin NBT delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOXT delete"
hide_output & spinner sg yiimpadmin "yiimp coin NXTI delete"
hide_output & spinner sg yiimpadmin "yiimp coin PIGGY delete"
hide_output & spinner sg yiimpadmin "yiimp coin PRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin RIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SJCX delete"
hide_output & spinner sg yiimpadmin "yiimp coin SQL delete"
hide_output & spinner sg yiimpadmin "yiimp coin SRCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SWARM delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNITY delete"
hide_output & spinner sg yiimpadmin "yiimp coin WOLF delete"
hide_output & spinner sg yiimpadmin "yiimp coin XWC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FSC2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin RBR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGD delete"
hide_output & spinner sg yiimpadmin "yiimp coin ARI delete"
hide_output & spinner sg yiimpadmin "yiimp coin XBS delete"
hide_output & spinner sg yiimpadmin "yiimp coin USDT delete"
hide_output & spinner sg yiimpadmin "yiimp coin GP delete"
hide_output & spinner sg yiimpadmin "yiimp coin CON delete"
hide_output & spinner sg yiimpadmin "yiimp coin EAGS delete"
hide_output & spinner sg yiimpadmin "yiimp coin NKA delete"
hide_output & spinner sg yiimpadmin "yiimp coin INCA delete"
hide_output & spinner sg yiimpadmin "yiimp coin XSP delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLK delete"
hide_output & spinner sg yiimpadmin "yiimp coin SBIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin UIS delete"
hide_output & spinner sg yiimpadmin "yiimp coin HGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin 2015 delete"
hide_output & spinner sg yiimpadmin "yiimp coin GMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin VMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ggggg delete"
hide_output & spinner sg yiimpadmin "yiimp coin UCI delete"
hide_output & spinner sg yiimpadmin "yiimp coin EQX delete"
hide_output & spinner sg yiimpadmin "yiimp coin TAK delete"
hide_output & spinner sg yiimpadmin "yiimp coin TEK delete"
hide_output & spinner sg yiimpadmin "yiimp coin TES delete"
hide_output & spinner sg yiimpadmin "yiimp coin TGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TOR delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNB delete"
hide_output & spinner sg yiimpadmin "yiimp coin USDe delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin XJO delete"
hide_output & spinner sg yiimpadmin "yiimp coin XLB delete"
hide_output & spinner sg yiimpadmin "yiimp coin YAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin YBC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZED delete"
hide_output & spinner sg yiimpadmin "yiimp coin ADT delete"
hide_output & spinner sg yiimpadmin "yiimp coin ASC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BAT delete"
hide_output & spinner sg yiimpadmin "yiimp coin COL delete"
hide_output & spinner sg yiimpadmin "yiimp coin CPR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CTM delete"
hide_output & spinner sg yiimpadmin "yiimp coin DBL delete"
hide_output & spinner sg yiimpadmin "yiimp coin DMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ELP delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLAP delete"
hide_output & spinner sg yiimpadmin "yiimp coin GME delete"
hide_output & spinner sg yiimpadmin "yiimp coin LEAF delete"
hide_output & spinner sg yiimpadmin "yiimp coin LOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin MEM delete"
hide_output & spinner sg yiimpadmin "yiimp coin MEOW delete"
hide_output & spinner sg yiimpadmin "yiimp coin MST delete"
hide_output & spinner sg yiimpadmin "yiimp coin RBBT delete"
hide_output & spinner sg yiimpadmin "yiimp coin RED delete"
hide_output & spinner sg yiimpadmin "yiimp coin TIPS delete"
hide_output & spinner sg yiimpadmin "yiimp coin TIX delete"
hide_output & spinner sg yiimpadmin "yiimp coin XNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZEIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin AC delete"
hide_output & spinner sg yiimpadmin "yiimp coin Acoin  delete"
hide_output & spinner sg yiimpadmin "yiimp coin AGS delete"
hide_output & spinner sg yiimpadmin "yiimp coin ALF delete"
hide_output & spinner sg yiimpadmin "yiimp coin ALN delete"
hide_output & spinner sg yiimpadmin "yiimp coin AMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ARG delete"
hide_output & spinner sg yiimpadmin "yiimp coin AUR delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BEN delete"
hide_output & spinner sg yiimpadmin "yiimp coin BET delete"
hide_output & spinner sg yiimpadmin "yiimp coin BNCR delete"
hide_output & spinner sg yiimpadmin "yiimp coin BOST delete"
hide_output & spinner sg yiimpadmin "yiimp coin BQC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTB delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTG delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CACH delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAP delete"
hide_output & spinner sg yiimpadmin "yiimp coin CASH delete"
hide_output & spinner sg yiimpadmin "yiimp coin CGB delete"
hide_output & spinner sg yiimpadmin "yiimp coin CINNI delete"
hide_output & spinner sg yiimpadmin "yiimp coin CMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CNL delete"
hide_output & spinner sg yiimpadmin "yiimp coin COMM delete"
hide_output & spinner sg yiimpadmin "yiimp coin COOL delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRACK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CSC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DEM delete"
hide_output & spinner sg yiimpadmin "yiimp coin DMD delete"
hide_output & spinner sg yiimpadmin "yiimp coin DRKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DT delete"
hide_output & spinner sg yiimpadmin "yiimp coin DVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin EAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ELC delete"
hide_output & spinner sg yiimpadmin "yiimp coin EMD delete"
hide_output & spinner sg yiimpadmin "yiimp coin EZC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FFC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLT delete"
hide_output & spinner sg yiimpadmin "yiimp coin FRAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin FRK delete"
hide_output & spinner sg yiimpadmin "yiimp coin FST delete"
hide_output & spinner sg yiimpadmin "yiimp coin GDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLD delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLX delete"
hide_output & spinner sg yiimpadmin "yiimp coin GLYPH delete"
hide_output & spinner sg yiimpadmin "yiimp coin GUE delete"
hide_output & spinner sg yiimpadmin "yiimp coin HBN delete"
hide_output & spinner sg yiimpadmin "yiimp coin HVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ICB delete"
hide_output & spinner sg yiimpadmin "yiimp coin IXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin JKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin KDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin KGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin LAB delete"
hide_output & spinner sg yiimpadmin "yiimp coin LGD delete"
hide_output & spinner sg yiimpadmin "yiimp coin LK7 delete"
hide_output & spinner sg yiimpadmin "yiimp coin LKY delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTB delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTCX delete"
hide_output & spinner sg yiimpadmin "yiimp coin LYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MED delete"
hide_output & spinner sg yiimpadmin "yiimp coin MNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MZC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NAN delete"
hide_output & spinner sg yiimpadmin "yiimp coin NBL delete"
hide_output & spinner sg yiimpadmin "yiimp coin NEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NRB delete"
hide_output & spinner sg yiimpadmin "yiimp coin NRS delete"
hide_output & spinner sg yiimpadmin "yiimp coin NYAN delete"
hide_output & spinner sg yiimpadmin "yiimp coin OSC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PHS delete"
hide_output & spinner sg yiimpadmin "yiimp coin Points delete"
hide_output & spinner sg yiimpadmin "yiimp coin PSEUD delete"
hide_output & spinner sg yiimpadmin "yiimp coin PTS delete"
hide_output & spinner sg yiimpadmin "yiimp coin PYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin RT2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin RYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SAT2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin SBC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHLD delete"
hide_output & spinner sg yiimpadmin "yiimp coin SILK delete"
hide_output & spinner sg yiimpadmin "yiimp coin SMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SOLE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPA delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPT delete"
hide_output & spinner sg yiimpadmin "yiimp coin SSV delete"
hide_output & spinner sg yiimpadmin "yiimp coin EMC2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin GIMP delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin KRYP delete"
hide_output & spinner sg yiimpadmin "yiimp coin MIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MOTO delete"
hide_output & spinner sg yiimpadmin "yiimp coin MSC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NWO delete"
hide_output & spinner sg yiimpadmin "yiimp coin PLCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin PROZ delete"
hide_output & spinner sg yiimpadmin "yiimp coin SONG delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPUDS delete"
hide_output & spinner sg yiimpadmin "yiimp coin SQC delete"
hide_output & spinner sg yiimpadmin "yiimp coin VOXP delete"
hide_output & spinner sg yiimpadmin "yiimp coin VTX delete"
hide_output & spinner sg yiimpadmin "yiimp coin XRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XSX delete"
hide_output & spinner sg yiimpadmin "yiimp coin XVG delete"
hide_output & spinner sg yiimpadmin "yiimp coin DON delete"
hide_output & spinner sg yiimpadmin "yiimp coin FJC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin GRN delete"
hide_output & spinner sg yiimpadmin "yiimp coin GUA delete"
hide_output & spinner sg yiimpadmin "yiimp coin HAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin HEX delete"
hide_output & spinner sg yiimpadmin "yiimp coin IFC delete"
hide_output & spinner sg yiimpadmin "yiimp coin IRL delete"
hide_output & spinner sg yiimpadmin "yiimp coin KARM delete"
hide_output & spinner sg yiimpadmin "yiimp coin MINT delete"
hide_output & spinner sg yiimpadmin "yiimp coin MOON delete"
hide_output & spinner sg yiimpadmin "yiimp coin MTLMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NMC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ORB delete"
hide_output & spinner sg yiimpadmin "yiimp coin PCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PHC delete"
hide_output & spinner sg yiimpadmin "yiimp coin RC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRL delete"
hide_output & spinner sg yiimpadmin "yiimp coin USD delete"
hide_output & spinner sg yiimpadmin "yiimp coin VTA delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPM delete"
hide_output & spinner sg yiimpadmin "yiimp coin BURST delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTCD delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRAIG delete"
hide_output & spinner sg yiimpadmin "yiimp coin TIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BSTY delete"
hide_output & spinner sg yiimpadmin "yiimp coin GNS delete"
hide_output & spinner sg yiimpadmin "yiimp coin DCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin PXI delete"
hide_output & spinner sg yiimpadmin "yiimp coin ROS delete"
hide_output & spinner sg yiimpadmin "yiimp coin STV delete"
hide_output & spinner sg yiimpadmin "yiimp coin OPAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXCL delete"
hide_output & spinner sg yiimpadmin "yiimp coin PYRA delete"
hide_output & spinner sg yiimpadmin "yiimp coin NET delete"
hide_output & spinner sg yiimpadmin "yiimp coin SEED delete"
hide_output & spinner sg yiimpadmin "yiimp coin PND delete"
hide_output & spinner sg yiimpadmin "yiimp coin GHC delete"
hide_output & spinner sg yiimpadmin "yiimp coin DOPE delete"
hide_output & spinner sg yiimpadmin "yiimp coin ONE delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLEU delete"
hide_output & spinner sg yiimpadmin "yiimp coin BVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin CDN delete"
hide_output & spinner sg yiimpadmin "yiimp coin CESC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CLR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CZC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHILD delete"
hide_output & spinner sg yiimpadmin "yiimp coin XQN delete"
hide_output & spinner sg yiimpadmin "yiimp coin RDD delete"
hide_output & spinner sg yiimpadmin "yiimp coin NXT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MYR-qubit delete"
hide_output & spinner sg yiimpadmin "yiimp coin UTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin 888 delete"
hide_output & spinner sg yiimpadmin "yiimp coin EFL delete"
hide_output & spinner sg yiimpadmin "yiimp coin DIME delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLR delete"
hide_output & spinner sg yiimpadmin "yiimp coin WATER delete"
hide_output & spinner sg yiimpadmin "yiimp coin NLG delete"
hide_output & spinner sg yiimpadmin "yiimp coin GIVE delete"
hide_output & spinner sg yiimpadmin "yiimp coin WC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOBL delete"
hide_output & spinner sg yiimpadmin "yiimp coin BITS delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLU delete"
hide_output & spinner sg yiimpadmin "yiimp coin OC delete"
hide_output & spinner sg yiimpadmin "yiimp coin THC delete"
hide_output & spinner sg yiimpadmin "yiimp coin ENRG delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHIBE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SFR delete"
hide_output & spinner sg yiimpadmin "yiimp coin NAUT delete"
hide_output & spinner sg yiimpadmin "yiimp coin VRC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CURE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SYNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XSI delete"
hide_output & spinner sg yiimpadmin "yiimp coin XC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDQ delete"
hide_output & spinner sg yiimpadmin "yiimp coin MMXIV delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAIX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BBR delete"
hide_output & spinner sg yiimpadmin "yiimp coin HYPER delete"
hide_output & spinner sg yiimpadmin "yiimp coin CCN delete"
hide_output & spinner sg yiimpadmin "yiimp coin KTK delete"
hide_output & spinner sg yiimpadmin "yiimp coin MUGA delete"
hide_output & spinner sg yiimpadmin "yiimp coin VOOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BN delete"
hide_output & spinner sg yiimpadmin "yiimp coin XMR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CLOAK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CHCC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BURN delete"
hide_output & spinner sg yiimpadmin "yiimp coin KORE delete"
hide_output & spinner sg yiimpadmin "yiimp coin RZR delete"
hide_output & spinner sg yiimpadmin "yiimp coin XDN delete"
hide_output & spinner sg yiimpadmin "yiimp coin MIN delete"
hide_output & spinner sg yiimpadmin "yiimp coin TECH delete"
hide_output & spinner sg yiimpadmin "yiimp coin GML delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRK delete"
hide_output & spinner sg yiimpadmin "yiimp coin WKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin QTL delete"
hide_output & spinner sg yiimpadmin "yiimp coin XXX delete"
hide_output & spinner sg yiimpadmin "yiimp coin AERO delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRUST delete"
hide_output & spinner sg yiimpadmin "yiimp coin BRIT delete"
hide_output & spinner sg yiimpadmin "yiimp coin JUDGE delete"
hide_output & spinner sg yiimpadmin "yiimp coin NAV delete"
hide_output & spinner sg yiimpadmin "yiimp coin XST delete"
hide_output & spinner sg yiimpadmin "yiimp coin APEX delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZET delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTCD delete"
hide_output & spinner sg yiimpadmin "yiimp coin KEY delete"
hide_output & spinner sg yiimpadmin "yiimp coin NUD delete"
hide_output & spinner sg yiimpadmin "yiimp coin TRI delete"
hide_output & spinner sg yiimpadmin "yiimp coin PES delete"
hide_output & spinner sg yiimpadmin "yiimp coin ICG delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNO delete"
hide_output & spinner sg yiimpadmin "yiimp coin ESC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PINK delete"
hide_output & spinner sg yiimpadmin "yiimp coin IOC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin RAW delete"
hide_output & spinner sg yiimpadmin "yiimp coin MAX delete"
hide_output & spinner sg yiimpadmin "yiimp coin LXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BOOM delete"
hide_output & spinner sg yiimpadmin "yiimp coin BOB delete"
hide_output & spinner sg yiimpadmin "yiimp coin UNAT delete"
hide_output & spinner sg yiimpadmin "yiimp coin MWC delete"
hide_output & spinner sg yiimpadmin "yiimp coin VAULT delete"
hide_output & spinner sg yiimpadmin "yiimp coin FC2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin SSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin BIG delete"
hide_output & spinner sg yiimpadmin "yiimp coin GB delete"
hide_output & spinner sg yiimpadmin "yiimp coin ROOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin AXR delete"
hide_output & spinner sg yiimpadmin "yiimp coin RIPO delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIBRE delete"
hide_output & spinner sg yiimpadmin "yiimp coin SHADE delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLEX delete"
hide_output & spinner sg yiimpadmin "yiimp coin XBOT delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCASH delete"
hide_output & spinner sg yiimpadmin "yiimp coin NKT delete"
hide_output & spinner sg yiimpadmin "yiimp coin TTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CLAM delete"
hide_output & spinner sg yiimpadmin "yiimp coin VTR delete"
hide_output & spinner sg yiimpadmin "yiimp coin SUPER delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOO delete"
hide_output & spinner sg yiimpadmin "yiimp coin XPY delete"
hide_output & spinner sg yiimpadmin "yiimp coin SMLY delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCENT delete"
hide_output & spinner sg yiimpadmin "yiimp coin DS delete"
hide_output & spinner sg yiimpadmin "yiimp coin FAIR delete"
hide_output & spinner sg yiimpadmin "yiimp coin EVENT delete"
hide_output & spinner sg yiimpadmin "yiimp coin HUC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CAT delete"
hide_output & spinner sg yiimpadmin "yiimp coin WDC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTM delete"
hide_output & spinner sg yiimpadmin "yiimp coin RMS delete"
hide_output & spinner sg yiimpadmin "yiimp coin ANC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MEC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MONA delete"
hide_output & spinner sg yiimpadmin "yiimp coin DGC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BCF delete"
hide_output & spinner sg yiimpadmin "yiimp coin SYS delete"
hide_output & spinner sg yiimpadmin "yiimp coin ULTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin CXC delete"
hide_output & spinner sg yiimpadmin "yiimp coin METAL delete"
hide_output & spinner sg yiimpadmin "yiimp coin SPR delete"
hide_output & spinner sg yiimpadmin "yiimp coin CBR delete"
hide_output & spinner sg yiimpadmin "yiimp coin FIND delete"
hide_output & spinner sg yiimpadmin "yiimp coin AM delete"
hide_output & spinner sg yiimpadmin "yiimp coin FUD delete"
hide_output & spinner sg yiimpadmin "yiimp coin ERM delete"
hide_output & spinner sg yiimpadmin "yiimp coin VIA delete"
hide_output & spinner sg yiimpadmin "yiimp coin CKC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTS delete"
hide_output & spinner sg yiimpadmin "yiimp coin DEAF delete"
hide_output & spinner sg yiimpadmin "yiimp coin HIC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BAY delete"
hide_output & spinner sg yiimpadmin "yiimp coin VIOR delete"
hide_output & spinner sg yiimpadmin "yiimp coin VPN delete"
hide_output & spinner sg yiimpadmin "yiimp coin MN delete"
hide_output & spinner sg yiimpadmin "yiimp coin EXE delete"
hide_output & spinner sg yiimpadmin "yiimp coin PFC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GSX delete"
hide_output & spinner sg yiimpadmin "yiimp coin BRXv2 delete"
hide_output & spinner sg yiimpadmin "yiimp coin ACHK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRYPT delete"
hide_output & spinner sg yiimpadmin "yiimp coin HLC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SWIFT delete"
hide_output & spinner sg yiimpadmin "yiimp coin ARCH delete"
hide_output & spinner sg yiimpadmin "yiimp coin GAIA delete"
hide_output & spinner sg yiimpadmin "yiimp coin WWC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XRP delete"
hide_output & spinner sg yiimpadmin "yiimp coin LMR delete"
hide_output & spinner sg yiimpadmin "yiimp coin MNE delete"
hide_output & spinner sg yiimpadmin "yiimp coin CRW delete"
hide_output & spinner sg yiimpadmin "yiimp coin VDO delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOPE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XWT delete"
hide_output & spinner sg yiimpadmin "yiimp coin DTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SMBR delete"
hide_output & spinner sg yiimpadmin "yiimp coin HYP delete"
hide_output & spinner sg yiimpadmin "yiimp coin QBK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CENT delete"
hide_output & spinner sg yiimpadmin "yiimp coin BLOCK delete"
hide_output & spinner sg yiimpadmin "yiimp coin CATC delete"
hide_output & spinner sg yiimpadmin "yiimp coin SCSY delete"
hide_output & spinner sg yiimpadmin "yiimp coin ABY delete"
hide_output & spinner sg yiimpadmin "yiimp coin BALLS delete"
hide_output & spinner sg yiimpadmin "yiimp coin QSLV delete"
hide_output & spinner sg yiimpadmin "yiimp coin U delete"
hide_output & spinner sg yiimpadmin "yiimp coin BYC delete"
hide_output & spinner sg yiimpadmin "yiimp coin BUN delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZER delete"
hide_output & spinner sg yiimpadmin "yiimp coin ZNY delete"
hide_output & spinner sg yiimpadmin "yiimp coin MRY delete"
hide_output & spinner sg yiimpadmin "yiimp coin CANN delete"
hide_output & spinner sg yiimpadmin "yiimp coin POT delete"
hide_output & spinner sg yiimpadmin "yiimp coin TAG delete"
hide_output & spinner sg yiimpadmin "yiimp coin RBY delete"
hide_output & spinner sg yiimpadmin "yiimp coin NOTE delete"
hide_output & spinner sg yiimpadmin "yiimp coin LTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin NVC delete"
hide_output & spinner sg yiimpadmin "yiimp coin 42 delete"
hide_output & spinner sg yiimpadmin "yiimp coin JBS delete"
hide_output & spinner sg yiimpadmin "yiimp coin LSD delete"
hide_output & spinner sg yiimpadmin "yiimp coin J delete"
hide_output & spinner sg yiimpadmin "yiimp coin SLG delete"
hide_output & spinner sg yiimpadmin "yiimp coin VIK delete"
hide_output & spinner sg yiimpadmin "yiimp coin RPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin XG delete"
hide_output & spinner sg yiimpadmin "yiimp coin DP delete"
hide_output & spinner sg yiimpadmin "yiimp coin MARYJ delete"
hide_output & spinner sg yiimpadmin "yiimp coin XMG delete"
hide_output & spinner sg yiimpadmin "yiimp coin RUBLE delete"
hide_output & spinner sg yiimpadmin "yiimp coin XCLD delete"
hide_output & spinner sg yiimpadmin "yiimp coin BST delete"
hide_output & spinner sg yiimpadmin "yiimp coin HNC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GXG delete"
hide_output & spinner sg yiimpadmin "yiimp coin BTX delete"
hide_output & spinner sg yiimpadmin "yiimp coin 007 delete"
hide_output & spinner sg yiimpadmin "yiimp coin LUX delete"
hide_output & spinner sg yiimpadmin "yiimp coin ACP delete"
hide_output & spinner sg yiimpadmin "yiimp coin STR delete"
hide_output & spinner sg yiimpadmin "yiimp coin PAC delete"
hide_output & spinner sg yiimpadmin "yiimp coin PPC delete"
hide_output & spinner sg yiimpadmin "yiimp coin MLS delete"
hide_output & spinner sg yiimpadmin "yiimp coin FLO delete"
hide_output & spinner sg yiimpadmin "yiimp coin PTC delete"
hide_output & spinner sg yiimpadmin "yiimp coin GUN delete"
hide_output & spinner sg yiimpadmin "yiimp coin DOGE delete"
echo "$GREEN Junk coin removal completed...$COL_RESET"


sudo rm -r $STORAGE_ROOT/yiimp/yiimp_setup
cd $HOME/multipool/yiimp_single
